### ISSUE TITLE
Unable to add database in codeql vs code extension

### ISSUE THREAD

**Issue by Shivam60** [github/vscode-codeql#1001]
**Describe the bug**
I am unable to open any database in vs code. The vs code extension keeps on saying that the path does not exists. 

**Version**
The CodeQL and VS Code version in which the bug occurs.

CodeQL extension version: 1.5.6 
CodeQL CLI version: 2.6.0 
Platform: win32 x64

**To reproduce**
Steps to reproduce the behavior.

Try to open any folder. 

**Expected behavior**
![image](https://user-images.githubusercontent.com/13963817/141860168-02b57883-fee8-49b6-8667-7a734d06f2c2.png)

**Additional context**

**Comment by aeisenberg** [comment]
The `src.zip` archive contains the sources for the database. The database itself is in the parent directory. Try adding the database from one directory up.

**Comment by Shivam60** [comment]
thanks, turns out this was a vscode issue

**Comment by kostasvl** [comment]
I had the same problem, until I discovered this: https://github.com/github/vscode-codeql/issues/1445. Basically, you can't have more than one databases opened. I had to remove the existing one first...
