### ISSUE TITLE
Sorting results causes the dropdown to not show other `query predicate` results

### ISSUE THREAD

**Issue by kjcolley7** [github/vscode-codeql#1005]
When viewing results of queries with multiple `query predicate`s, if you click one of the column headers to sort by that column, you can no longer view the other `query predicate` results in the dropdown unless you go to a previous set of results and back again.

**Version**
CodeQL extension version: 1.5.6 CodeQL CLI version: 2.7.0 Platform: darwin x64

**To reproduce**
Save this query as `resultsBug.ql` and run on any database:
```ql
query predicate foo(string s) {
	s = "foo"
}

query predicate bar(string s) {
	s = "bar"
}
```

Click the dropdown. Notice how you see `foo`, `bar`, and `alerts`. In the dropdown, select `foo`. Click the column header for `s` to sort by that column. Now click the dropdown again. Notice how you now only see `foo` and `alerts`, and that `bar` is missing.

**Expected behavior**
After sorting one `query predicate`'s results by some column, I am still able to switch back to other `query predicate` results with the dropdown.

**Comment by aeisenberg** [comment]
Thanks for the bug report. I am able to reproduce this.

**Comment by aeisenberg** [comment]
Yes...I see that when the extension loads a sorted table, it is loading a different bqrs file that has partial results (only the results for that table). Should be simple to fix by ensuring that when we load a sorted table, we _also_ load the original bqrs file just to get all the table names.
