### ISSUE TITLE
[Help Wanted] MacOS extensions cannot access external codeql binary

### ISSUE THREAD

**Issue by kmahyyg** [github/vscode-codeql#1060]
**Describe the bug**

CodeQL extension logging output:

```
Starting GitHub.vscode-codeql extension
Checking CodeQL version using CodeQL CLI: /Users/<REDACTED FOR PRIVACY>/bin/codeql version -v --log-to-stderr --format=terse...
Failed to run 'codeql version'. Reason: Checking CodeQL version failed: Error: spawn /Users/<REDACTED FOR PRIVACY>/bin/codeql EACCES
CodeQL CLI is installed externally so could not be updated.
Checking CodeQL version using CodeQL CLI: /Users/<REDACTED FOR PRIVACY>/bin/codeql version -v --log-to-stderr --format=terse...
Failed to run 'codeql version'. Reason: Checking CodeQL version failed: Error: spawn /Users/<REDACTED FOR PRIVACY>/bin/codeql EACCES
Compatibility with the configured CodeQL CLI could not be determined. You may experience problems using the extension.
Initializing configuration listener...
Initializing CodeQL cli server...
Initializing query server client.
Checking CodeQL version using CodeQL CLI: /Users/<REDACTED FOR PRIVACY>/bin/codeql version -v --log-to-stderr --format=terse...
Failed to run 'codeql version'. Reason: Checking CodeQL version failed: Error: spawn /Users/<REDACTED FOR PRIVACY>/bin/codeql EACCES
Starting CodeQL CLI Server using CodeQL CLI: /Users/<REDACTED FOR PRIVACY>/bin/codeql execute cli-server -v --log-to-stderr
```

**Version**

CodeQL:
```
╰─○ codeql -V
CodeQL command-line toolchain release 2.7.2.
Copyright (C) 2019-2021 GitHub, Inc.
Unpacked in: /Users/<REDACTED FOR PRIVACY>/bin/codeql
   Analysis results depend critically on separately distributed query and
   extractor modules. To list modules that are visible to the toolchain,
   use 'codeql resolve qlpacks' and 'codeql resolve languages'.
```

VSCode:

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
```

**To reproduce**

A brand new environment.
- Download releases binaries zipped file from `https://github.com/github/codeql-cli-binaries/releases` using `codeql-osx64.zip`
- Unzip to `~/bin/codeql`
- `chmod +x ~/bin/codeql/codeql`
- Set extension settings inside VSCode using UI,  corresponding to JSON is: `"codeQL.cli.executablePath": "/Users/<REDACTED FOR PRIVACY>/bin/codeql"`
- Restart VSCode
- Click CodeQL Extension

**Expected behavior**

Run properly.

**Additional context**

I've already granted "Full Disk Access" to VsCode app itself previously on my Mac. And also `chmod +x ~/bin/codeql/codeql`.

The binary path of codeql in VsCode CodeQL extension is set to `/Users/<REDACTED FOR PRIVACY>/bin/codeql`.

I guess it is caused by Sandbox mechanism on MacOS.

The possible solutions might be:

- Have another copy inside the path of `~/.vscode/<Corresponding plugin>`, but I do not know the correct path.
- Something might could safely "bypass" this restriction in some way.

**Comment by aeisenberg** [comment]
Your executable path must be the full path to the executable, not the folder that contains it. Try setting this value:

```
"codeQL.cli.executablePath": "/Users/<REDACTED FOR PRIVACY>/bin/codeql/codeql"
```

**Comment by kmahyyg** [comment]
Thanks for your help. Problem resolved.

**Comment by Aerfa21** [comment]
> Your executable path must be the full path to the executable, not the folder that contains it. Try setting this value:
> 
> ```
> "codeQL.cli.executablePath": "/Users/<REDACTED FOR PRIVACY>/bin/codeql/codeql"
> ```

i also suffered the problem. Solved ,thanks
