### ISSUE TITLE
Add a `ready-for-doc-review` label to this repository

### ISSUE THREAD

**Issue by b4mboo** [github/vscode-codeql#1062]
**Is your feature request related to a problem? Please describe.**
The Docs Content team uses an automation to facilitate pings to the respective group of writers to review any user-facing changes. It relies on a `ready-for-doc-review` label to work as expected.

**Describe the solution you'd like**
Add a `ready-for-doc-review` label to this repository.

**Describe alternatives you've considered**
We want to deprecate the `@github/docs-content-codeql` team. The alternative to adding aforementioned label would be ping the wider Docs Content team, but that's not ideal.

**Additional context**
Related PR: https://github.com/github/vscode-codeql/pull/1061

**Comment by adityasharad** [comment]
Done! https://github.com/github/vscode-codeql/labels/ready-for-doc-review
