### ISSUE TITLE
Internal error in VS Code

### ISSUE THREAD

**Issue by kaeluka** [github/vscode-codeql#1081]
**Describe the bug**
I got an "Internal error. (codeQL.codeLensQuickEval)" error dialog in vscode.

**Version**
CodeQL extension version: 1.5.9 
CodeQL CLI version: 2.7.2 
Platform: darwin x64

Vs code:
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.4.0

**To reproduce**
The way to reproduce it for me is:
- open TaintedPathCustomizations.qll, line 452 (in the `blocks` predicate).
- Remove `.getBaseString()`.
- Quick evaluate the predicate.

**Expected behavior**
A graceful error.

**Additional context**
When this modification is present in the code base, unrelated queries will also fail. This might make it quite hard to find the root cause of the problem in some instances.

But this is not blocking me at all, I just thought that someone might find it valuable to be made aware.

This part of the output seems relevant:

```
SEVERE: Internal error: com.semmle.util.exception.CatastrophicError: Ambiguous super dispatch: method Node.asExpr() can be reached through extends and instanceof supertypes.
java.util.concurrent.CompletionException: com.semmle.util.exception.CatastrophicError: Ambiguous super dispatch: method Node.asExpr() can be reached through extends and instanceof supertypes.
```

![image](https://user-images.githubusercontent.com/775711/149957594-c8329d09-732e-48f0-8c62-64f55c669db8.png)

**Comment by aeisenberg** [comment]
Thank you for logging this error. I think we need some better error handling around invalid quick queries. At the very least, better error messages would be helpful.

**Comment by kaeluka** [comment]
Cool, glad if it can be helpful :)

**Comment by aeisenberg** [comment]
I have a fix for this. There's no easy way to get a better error message out of this since the error is coming from inside the compiler. Instead, the best we can do is wrap the error message to make it slightly more understandable and open up the query server logs (instead of the extension logs) since these logs will usually contain more information for malformed queries.

**Comment by Drun1baby** [comment]
so how can I solve this issue ……

**Comment by aeisenberg** [comment]
@Drun1baby, please open a new issue for your problem. Include any relevant messages from the CodeQL Extension output view and the Query Server output view.
