### ISSUE TITLE
Migrate to new vscode testing APIs

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#1099]
Currently, this extension uses the [UI test explorer](https://github.com/hbenl/vscode-test-explorer) as a ui for testing. However, this extension has recently become deprecated due to the release of [native APIs for testing](https://code.visualstudio.com/api/extension-guides/testing).

We should migrate to this new API. It will simplify our development since this extension would no longer have any dependencies on a third party extension.

Here is a [migration guide](https://code.visualstudio.com/api/extension-guides/testing). 

Note that when we change this, we can also change the devcontainer files on the vscode-codeql starter repo to avoid installing the test UI extension by default.

**Comment by aeisenberg** [comment]
Duplicate of #1085.

**Comment by dbartol** [comment]
Reopened because #1085 is now more focused on publishing to open-vsx, and moving to the new testing API was just one possible solution.

**Comment by adityasharad** [comment]
We're ready: will inform internal developers first and then switch.

**Comment by aeisenberg** [comment]
@dbartol Is it time to enable this unconditionally? Considering that we've been using this internally for 8 months with no problems, I think it's safe.

**Comment by dbartol** [comment]
Yeah, it's definitely time.  #3232
