### ISSUE TITLE
Support importing databases directly from github

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#1123]
For github repositories that save a copy of their databases, the extension should have a command that downloads and installs the database, similar to how we do it for LGTM databases.

There is already an API endpoint available:

```
gh api /repos/{owner}/{repo}/code-scanning/codeql/databases/<lang>
```

Is there a way to determine which database languages are available for any given repo before downloading?

**Comment by aibaars** [comment]
> Is there a way to determine which database languages are available for any given repo before downloading?

@rneatherway ^ ?

**Comment by rneatherway** [comment]
Sorry, no, there isn't currently any way to do that.

**Comment by aibaars** [comment]
@rneatherway Would it make sense for an REST API endpoint to list the available databases:

`gh api /repos/{owner}/{repo}/code-scanning/codeql/databases`

**Comment by rneatherway** [comment]
Yes, that definitely sounds sensible to explore :+1:

**Comment by shati-patel** [comment]
### Update

https://github.com/github/vscode-codeql/pull/1229 will add a "Download database from GitHub" command for internal users. Once MRVA (and specifically the `/code-scanning/codeql/databases` API) is more widely available, we can make this public.
