### ISSUE TITLE
AST viewer does not highlight corresponding node when clicking in the source file

### ISSUE THREAD

**Issue by nickrolfe** [github/vscode-codeql#1224]
### Describe the bug
Clicking on a location in the source file no longer causes the corresponding node to be highlighted in the AST viewer's tree. 

I note that the opposite interaction works: if you click on a node in the AST viewer, the corresponding location in the source file is selected/highlighted.

### Version
From what I can tell by trying some old versions of the extension, this worked as of 1.5.10 and is broken in 1.5.11 onwards.

### To reproduce
Open a source file in a database, and run 'View AST.' Click various elements in the source file and notice that the selection in the AST viewer's tree does not change.

**Comment by aeisenberg** [comment]
Thanks for raising this issue. I see that the problem is related to some refactoring I implemented to help add the graph viewer.
