### ISSUE TITLE
Path viewer shows empty line for `file://` locations

### ISSUE THREAD

**Issue by hvitved** [github/vscode-codeql#1357]
**Describe the bug**
When a `@kind path-problem` query has a path node whose SARIF `"location"` is `file:/`, then the SARIF `"message"` is ignored, and a completely empty entry is displayed:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/3667920/169266553-3718e387-8f91-4684-948b-874ec51d846d.png">

Example SARIF: [interpretedResults.sarif.zip](https://github.com/github/vscode-codeql/files/8728051/interpretedResults.sarif.zip)

**Version**
Latest

**Expected behavior**
Render the line with the provided `"message"`, but without a location link.

**Comment by aeisenberg** [comment]
First question I have is why are we getting all of these invalid file locations?

**Comment by aeisenberg** [comment]
I assume the query you are using is this one: `ruby/ql/src/queries/security/cwe-1333/PolynomialReDoS.ql`. Can you let me know what database you are using?

**Comment by MathiasVP** [comment]
Here's a recent Swift example I hit:

![Image](https://github.com/github/vscode-codeql/assets/4527323/06864bf5-65a1-4ac6-b833-3eb8f2733782)

The query is here:
```ql
/**
 * @kind path-problem
 */

import swift
import codeql.swift.dataflow.DataFlow
import Partial::PartialPathGraph

module Config implements DataFlow::ConfigSig {
  predicate isSource(DataFlow::Node source) {
    exists(CallExpr call |
      source.asExpr() = call and
      call.getStaticTarget().hasName("source()")
    )
  }

  predicate isSink(DataFlow::Node sink) {
    exists(CallExpr call |
      sink.asExpr() = call.getAnArgument().getExpr() and
      call.getStaticTarget().getName().matches("%sink%")
    )
  }
}

module Flow = DataFlow::Global<Config>;

int limit() { result = 10 }

module Partial = Flow::FlowExploration<limit/0>;

from Partial::PartialPathNode source, Partial::PartialPathNode sink
where Partial::partialFlow(source, sink, _) and not exists(sink.getASuccessor())
select sink.getNode(), source, sink, ""

```

And the database is here:

[quick-queries.testproj.zip](https://github.com/github/vscode-codeql/files/13069429/quick-queries.testproj.zip)
