### ISSUE TITLE
Error when trying to view the CSV results of a quick evaluation

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#1376]
1. Perform a quick evaluation anywhere
2. After the results view opens, Click on View CSV results for this query in the history view
3. BUG
```
Exception caught at top level: /Users/andrew.eisenberg/Library/Application Support/Code/User/globalStorage/github.vscode-codeql/queries/ExternalFlow.qll-utKlrrgKpMXWbhpVDQOh2/results.bqrs has no result set called #select.
                      com.semmle.cli2.bqrs.DecodeCommand.generateOutput(DecodeCommand.java:237)
                      com.semmle.cli2.bqrs.DecodeCommand.executeSubcommand(DecodeCommand.java:213)
                      com.semmle.cli2.picocli.SubcommandCommon.executeWithParent(SubcommandCommon.java:484)
                      com.semmle.cli2.execute.CliServerCommand.lambda$executeSubcommand$0(CliServerCommand.java:67)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:205)
                      com.semmle.cli2.execute.CliServerCommand.executeSubcommand(CliServerCommand.java:67)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:500)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:205)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:214)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:98)
```

What's happening is that the view CSV results is expecting a `#select` results set, but in this case, the results set does not exist. The only results set available is some renaming of the selected quick eval text.

I can think of two possible solutions:

1. Turn off csv results for quick eval (not great)
2. Arbitrarily choose a single results set to view if the `#select` results set is not available. 99% of the time (maybe 100% of the time) this will do the right thing.

**Comment by adityasharad** [comment]
Can we get the correct result set name using `bqrs info`? I expect there to be only one result set.

**Comment by aeisenberg** [comment]
If there is more than one result set, what does it mean to be "correct"? (Maybe it's the result set prefixed by `#`?)

If there is exactly one result set, do we even need the name of the result set? We just need to get the single set.

In the case of quick eval, I think there's only one result set.
