### ISSUE TITLE
Dumping CSV does not escape ',' character from results

### ISSUE THREAD

**Issue by JLLeitschuh** [github/vscode-codeql#1377]
**Describe the bug**

Execute the following CodeQL query:

```
import java
import semmle.code.java.dataflow.ExternalFlow

from string namespace, string type, boolean subtypes, string name, string signature, string ext,
  string input, string output, string kind, boolean generated, string row
where summaryModel(namespace, type, subtypes, name, signature, ext, input, output, kind, generated, row)
select namespace, type, subtypes, name, signature, ext, input, output, kind, generated, row
```

Then "Views Results CVS" on the result.

The output CVS will not have the `,` in entries escaped properly.

**Version**

```
CodeQL extension version: 1.6.5 
CodeQL CLI version: 2.9.1 
Platform: darwin arm64
```

**To reproduce**

See above

**Expected behavior**

Output CSV should escape the `,` character in entries

**Additional context**

**Comment by aeisenberg** [comment]
Thanks for reporting. I can reproduce the error.

**Comment by aeisenberg** [comment]
Problem is here: https://github.com/github/vscode-codeql/blob/2f9aca785e5e6c5616b3b3c20e360b1f68096db4/extensions/ql-vscode/src/run-queries.ts#L362

The `const chunk: DecodedBqrsChunk` that gets returned contains `tuples` and `columns`. The columns contain type information. Each string column should be quoted.
