### ISSUE TITLE
"Open Variant Analysis on GitHub" is offered for failed / cancelled local queries

### ISSUE THREAD

**Issue by Marcono1234** [github/vscode-codeql#1495]
**Describe the bug**
When a _local_ query fails or is cancelled the context menu for the Query History entry offers "Open Variant Analysis on GitHub". This behavior seems to be incorrect.

Might be related to the needed refactoring mentioned in #1325.

**Version**
Extension:
```
CodeQL extension version: 1.6.12 
CodeQL CLI version: 2.10.4 
Platform: win32 x64
```

VS Code:
```
Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No
```

**To reproduce**
1. Try to run a query with compilation errors locally; or alternatively cancel a local query
2. Open the CodeQL tab
3. Right-click the respective entry in the Query History list
:x: It offers "Open Variant Analysis on GitHub"

**Expected behavior**
"Open Variant Analysis on GitHub" should not be offered for failed local queries.

**Comment by charisk** [comment]
Thanks for raising this with excellent description and repro steps @Marcono1234!
