### ISSUE TITLE
The extension should be converted to `Extension Pack` as it also installs 'Test Adapter Converter' and 'Test Explorer UI'

### ISSUE THREAD

**Issue by darkred** [github/vscode-codeql#1542]
**Describe the bug**
The extension should be converted to `Extension Pack` as it also installs 2 additional extensions: 'Test Adapter Converter' and 'Test Explorer UI'.

**Version**
CodeQL extension: v1.7.0
CodeQL CLI version: v2.10.5 *(irrelevant)*
VSCode: 1.71.2
Platform: Win11 x64

**To reproduce**
- In a fresh VSCode installation, install latest CodeQL extension v1.7.0 .
- Then open VSCode's 'Extensions' panel (Ctrl+Shift+X). See that 3 extensions have been installed instead:
  - 'CodeQL'
  - 'Test Adapter Converter'
  - 'Test Explorer UI' 
  &nbsp;
  <details>
  <summary>Screenshot:</summary>
   
  ![2022-09-24_210625~](https://user-images.githubusercontent.com/723651/192118386-a89fd018-0337-4028-8b9a-a9fc80e06afb.jpg)
  </details>

**Expected behavior**
The current expected behavior is to have 1 extension, not 3.  
So, the extension should be converted to `Extension Pack` for two reasons:
1. Most importantly to inform the user about the 2 additional installed extensions. Also, changing the extension to a Pack, its entry in Extensions tab will get a count badge.
2. When the user disables the 'CodeQL' main extension, the other 2 extensions to become disabled as well.

**Additional context**
Related info about Extension Packs: https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup.

Also, trying to disable the 'Test Adapter Converter' extension alone results in this notification:
> Cannot disable 'Test Adapter Converter' extension alone. 'Test Explorer UI' extension depends on this. > Do you want to disable all these extensions?
<details>
<summary>Screenshot:</summary>

![2022-09-25_002441](https://user-images.githubusercontent.com/723651/192119325-94529d1f-5abb-4468-942c-9260aad4f763.jpg)
</details>

**Comment by aeisenberg** [comment]
Thank you for raising this issue. We are not considering creating an extension pack at this time. The extensions that the vscode-codeql extension uses are dependencies and are required for proper functionality. Extension packs are generally used when you want to bundle a list of curated extensions together. This is not the situation we have with vscode-codeql. Please let me know if this is preventing you from doing what you need to do and we can reconsider.

**Comment by darkred** [comment]
I believe that the fact that 2 additional extensions are dependencies required for proper functionality, should be clearly noted in the [Marketplace](https://marketplace.visualstudio.com/items?itemName=github.vscode-codeql) page (and the 'Details' tab of the VSCode's Extensions panel) as well in the github [README.md](https://github.com/github/vscode-codeql/blob/main/README.md) .

&nbsp;
Also, as seen in the screenshot from the Extensions panel, the authors of 2 extra extensions are different than that of CodeQL:
![2022-09-26_185336](https://user-images.githubusercontent.com/723651/192325040-3e549b4a-2888-4cc8-844b-cccacb33ad7e.jpg)

- **CodeQL** itself is authored by GitHub *(verified ownership of github.com)*
- **Test Adapter Converter** is authored by Microsoft *(verified ownership of microsoft.com)*
- **Test Explorer UI** is authored by Holger Benl *(no verified domain badge)*.

I was puzzled when I realized the existense of the 2 extra extensions. I couldn't tell how they could have been installed. That's why I made this issue. Yes, the extra extensions are very popular ones, nevertheless I think that the user deserves to know before installing the extension.

**Comment by darkred** [comment]
@aeisenberg If you find it useful, I could make a PR for [README.md](https://github.com/github/vscode-codeql/blob/main/README.md) with the following addition:

```markdown
vscode-codeql installs the following two extensions: 
- [Test Adapter Converter](https://github.com/microsoft/vscode-test-adapter-converter)
- [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer)

They are dependencies and are required for proper functionality.
```

**Comment by aeisenberg** [comment]
That sounds reasonable. Feel free to raise a PR. Thank you.
