### ISSUE TITLE
Database import fails when folder is prefixed with `db-`

### ISSUE THREAD

**Issue by hvitved** [github/vscode-codeql#1561]
**Describe the bug**

<img width="450" alt="image" src="https://user-images.githubusercontent.com/3667920/193562532-3c59b8db-3ab8-417b-9efd-c6c9246bbaf8.png">

It is not a big problem, except the DBs we download from DCA all contain this prefix.

**Comment by hvitved** [comment]
Ping @esbena so you are aware as well (perhaps the easiest fix is just for DCA to not add the `db-` prefix).

**Comment by esbena** [comment]
Can you check if `database-` is an acceptable prefix?

**Comment by hvitved** [comment]
It is.

**Comment by aeisenberg** [comment]
I put in a fix.
