### ISSUE TITLE
Extension fails to realise that database needs to be upgraded

### ISSUE THREAD

**Issue by max-schaefer** [github/vscode-codeql#168]
Steps to reproduce:

  1. Download any JavaScript database from LGTM.com, import it into VSCode
  2. Open a version of https://github.com/Semmle/ql that includes https://github.com/Semmle/ql/pull/2252; this PR introduces a dbscheme change that isn't on LGTM.com yet
  3. Try running a JavaScript query

The query fails to run, and opening the Query Server log reveals that this is due to a dbscheme mismatch, yet the dialog for automatically upgrading the database before running the query does not appear. Manually upgrading the database fixes the problem.

(This is the underlying bug causing https://github.com/Semmle/ql/issues/2354.)

**Comment by jcreedcmu** [comment]
Am able to reproduce, trying to figure out why it's happening.
