### ISSUE TITLE
Feature request: QLDoc continuation on new line

### ISSUE THREAD

**Issue by Cornelius-Riemenschneider** [github/vscode-codeql#171]
Hi,

The QL plugin for eclipse has the nice feature that when I write a QLdoc block comment,
it adds the * and indents correctly whenever I press enter on a newline.
The VSCode plugin doesn't provide this.
For other languages, https://marketplace.visualstudio.com/items?itemName=kevinkyang.auto-comment-blocks is available, which seems to achieve what I want.

**Comment by adityasharad** [comment]
Hi @Cornelius-Riemenschneider, thanks for your feedback and the useful reference! We’re working on it and will keep you posted.

**Comment by aeisenberg** [comment]
I think there are a few easy things we can do here to make the commenting experience better.
