### ISSUE TITLE
Inconsistent source code highlighting

### ISSUE THREAD

**Issue by Cornelius-Riemenschneider** [github/vscode-codeql#188]
Hi,
in the screenshot below it can be seen that the code highlighting is inconsistent.
In particular, the first occurrences of "query", "a" and "b" in the QL code are in the wrong colour.

![2019-12-04-200621_1020x331_scrot](https://user-images.githubusercontent.com/70492/70172894-f570ae80-16d1-11ea-95ab-d990b52288bf.png)
Although the image was taken a private branch, the issue is reproducible with current master and version 1.0.1 of the CodeQL plugin.

**Comment by jcreedcmu** [comment]
Can't reproduce, seems to highlight correctly for me. Feel free to reopen if it's still broken for current version of the extension.
