### ISSUE TITLE
Negative integers are returned as unsigned integers

### ISSUE THREAD

**Issue by kachakil** [github/vscode-codeql#191]
According to the documentation, `int` is "_The primitive type of integers, represented with 32 bits using two's complement_". However, the VS Code extension returns `4294967295` (instead of `-1`) for the following queries, among other similar expressions:

```sql
from int x
where x = -1
select x
```
```sql
select -1
```

![screenshot-uint-ql](https://user-images.githubusercontent.com/6338850/70460693-380dfe80-1ab7-11ea-8708-2f15953244a5.png)

**Comment by adityasharad** [comment]
Thank you very much for the report. This has been fixed by https://github.com/github/vscode-codeql/pull/192.
