### ISSUE TITLE
Support sorting for interpreted alerts

### ISSUE THREAD

**Issue by jhelie** [github/vscode-codeql#196]
At the moment it is possible to sort results by each column in the `#select` view. However the interpreted `alerts` is very useful and could also benefit for some similar dynamic sorting for better exploration of the results..

Would it be possible to add some "sorting" columns to the `#alerts` view? I'm not sure exactly what this would like but the idea would be to keep the clean and readable look of interpreted alerts while also having a way to re-arrange their order (maybe a "sort by" dropdown with all the variables in the select clause as options?)

**Comment by jcreedcmu** [comment]
@github/product-docs-dsp this is something we'd like to release that has user-facing changes. How much lead time would you like before releasing this, assuming the PR lands soon?

**Comment by jf205** [comment]
Thanks for the mention @jcreedcmu. It's difficult to say without more details or context. Is there an implementation PR open yet?

**Comment by jcreedcmu** [comment]
Yes, the #232 linked above.

**Comment by shati-patel** [comment]
> @github/product-docs-dsp this is something we'd like to release that has user-facing changes. How much lead time would you like before releasing this, assuming the PR lands soon?

Thanks again for letting us know @jcreedcmu! I've had a look, and this doesn't currently affect the docs. We don't mention anything about result sorting yet, so I'll rework the linked [docs issue](https://github.com/github/product-documentation/issues/2194) to remind us to add details about that in the future (this doesn't block a release).

As long as the changelog is updated, this is good to release any time! :shipit:
