### ISSUE TITLE
Graph viewer: blocked by CSP?

### ISSUE THREAD

**Issue by hmac** [github/vscode-codeql#2077]
**Describe the bug**
Previously, running a graph query would render the results in the graph viewer. Now, the results view shows but no graph is rendered. Instead, the console shows this error:

```
webview.js:1696 Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -sASSERTIONS for more info.
    at $ (webview.js:1696:87261)
    at webview.js:1696:130912
```

**Version**
CodeQL extension version: 1.7.8 
CodeQL CLI version: 2.12.2 
Platform: darwin x64

**To reproduce**
With a database selected, run a `@kind graph` query.

**Expected behavior**
The results view should render a graph.

**Additional context**
It seems that the CSP policy now disallows the wasm that `d3-graphviz` evaluates to render the graph. But I'm not super familiar with internals of this extension so I may be mistaken.

**Comment by koesie10** [comment]
Thanks for reporting the issue and figuring out that this means that the CSP disallows loading the WASM module! This should be fixed by #2085.
