### ISSUE TITLE
"ERROR: The selection is not a valid quick-eval target" for classes

### ISSUE THREAD

**Issue by Cornelius-Riemenschneider** [github/vscode-codeql#213]
Hi,

when quick-evaluating the name of a class in a class definition, I get the error

> Quick evaluation compilation failed: 
ERROR: The selection is not a valid quick-eval target. (/home/qldev/build/ql/cpp/ql/src/semmle/code/cpp/ir/implementation/aliased_ssa/Instruction.qll:648:19:648:19)

When evaluating the predicate with the name of the class, I get meaningful results.
Maybe it would be a good idea to redirect from the class definition to the defining predicate when using quick-eval?

**Comment by p0** [comment]
Agreed, the name of a (finite) class should be a valid quick-eval target. Thanks for the suggestion!

**Comment by ginsbach** [comment]
https://git.semmle.com/Semmle/code/pull/36518
