### ISSUE TITLE
CodeQL CLI enter path to executable creates odd query failures

### ISSUE THREAD

**Issue by knewbury01** [github/vscode-codeql#2199]
**Describe the bug**
CodeQL extension shows red error squiggles but is able to execute query.
This happens to me specifically when:
1) I have some CLI version already in the User space (2.10.5) - not sure if this part is relevant.
2) I download a bundle version of CodeQL CLI (2.12.2)
3) I update the workspace CodeQL path from empty to the 2.12.2 path
4) open any query that I am working on , and the query shows the red errors, with the following message, but still executes.

<img width="507" alt="Screenshot 2023-03-21 at 8 02 15 PM" src="https://user-images.githubusercontent.com/22016146/226768505-ad2f9a0d-24c7-4a9a-9e05-4f4c65f143c2.png">

**Additionally** , reload window does make the error squiggles go away , but then the query actually becomes un-runnable, seemingly no matter what else is done.

<img width="532" alt="Screenshot 2023-03-21 at 8 05 53 PM" src="https://user-images.githubusercontent.com/22016146/226769000-7ecf8b43-b55b-43ad-a56d-874327322cec.png">

**Version**
The CodeQL and VS Code version in which the bug occurs.

CodeQL version: 2.12.2
CodeQL extension version: 1.8.0

**To reproduce**
listed above.
sample query:
```
 import java

from Expr e 
select e
```
sample qlpack.yml:
```
name: testworkshop
version: 0.0.0
dependencies:
    codeql/java-all: "*"
```

**Expected behavior**
No red squiggles present. and for reload window to not mysteriously break the environment.

**Additional context**

**Comment by knewbury01** [comment]
> I'm thinking that the error with running the queries has to do with using the bundle. As a workaround, can you try using a non-bundle version of the CLI? (It's _supposed_ to work with a bundle, but it's looking like for some reason, there is an issue).

yep you were totally right, tried it today with a pack install and just CLI binary workflow and the reload window does clear up the error message!

**Comment by aeisenberg** [comment]
I tried a few ways to reproduce this part of the error:

> Additionally, reload window does make the error squiggles go away, but then the query actually becomes un-runnable, seemingly no matter what else is done.

but I could not. 

It sounds like you are currently unblocked and there are no more reproducible errors, so I'll be closing this issue.
