### ISSUE TITLE
CodeQL CLI enter path to executable gets reset after DB entry

### ISSUE THREAD

**Issue by knewbury01** [github/vscode-codeql#2226]
**Describe the bug**
CodeQL CLI enter path to executable gets reset after DB entry, specifically when : 

1) I already have a CLI version entered in the User view
2) I add a different CLI version into the Workspace view
3) I add a DB to the editor
4) the query server restarts and the Workspace view CLI gets removed

**Version**
The CodeQL and VS Code version in which the bug occurs.

I have observed this with several pairings of versions, but latest observation:
VSCode CodeQL extension: 1.8.1
CodeQL CLI in User view: 2.10.5
CodeQL CLI in Workspace view: 2.12.4

**To reproduce**
listed above

**Expected behavior**
adding a database ideally should not force me to go back and re enter the CLI in the workspace view path

**Additional context**

**Comment by aeisenberg** [comment]
When this happens are you originally in a single rooted workspace and does adding a database move you to a mult-root workspace? If so, this behaviour is understandable.

**Comment by knewbury01** [comment]
> When this happens are you originally in a single rooted workspace and does adding a database move you to a mult-root workspace? If so, this behaviour is understandable.

ah so any time the DB is not in the subdirectory of the folder already open then this is expected? 

then yeah this is what I see happening, thanks for looking into it!
