### ISSUE TITLE
Variant Analysis Results shows green check mark despite some failures

### ISSUE THREAD

**Issue by Marcono1234** [github/vscode-codeql#2239]
**Describe the bug**
The "REPOSITORIES" progress at the top of the Variant Analysis Results shows a green check mark despite the fact that the query failed for some projects:
![Results screenshot](https://user-images.githubusercontent.com/11685886/227743888-13130818-dd69-44a7-9ebc-4e9fb73adae8.png)

**Version**
Extension version:
```
CodeQL extension version: 1.8.1 
CodeQL CLI version: 2.12.5 
Platform: win32 x64
```

VS Code version:
```
Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

**To reproduce**
1. Run a Variant Analysis query
2. Cause the query to fail for some projects (?)
Not sure if there is a proper way to reproduce this, in my case it failed due to "Request to https://objects-origin.githubusercontent.com/codeql-query-console returned status code 504" ([action log](https://github.com/Marcono1234/codeql-java-queries/actions/runs/4521280205/jobs/7962939033))
3. Open the Variant Analysis Results view and wait until all queries are completed
:x: Bug: The "REPOSITORIES" information at the top shows "100 / 100 ✔️"

**Expected behavior**
It should not show a green check mark, and maybe similar to a cancelled query run show a warning box informing the user that the query failed for some projects.

**Comment by jf205** [comment]
Hi @Marcono1234. Thanks for the feedback ❤️ . Someone from our team is going to look into this.

**Comment by stonish** [comment]
For anyone who is curious, here ids the [issue](https://github.com/github/code-scanning/issues/9636) where we will investigate this behaviour.

**Comment by robertbrignull** [comment]
Should be addressed by https://github.com/github/vscode-codeql/pull/2349, which will be released at the latest in two weeks time.
