### ISSUE TITLE
ESC key closes current running query notification

### ISSUE THREAD

**Issue by Cornelius-Riemenschneider** [github/vscode-codeql#227]
**Is your feature request related to a problem? Please describe.**
When pressing the escape key to get rid of an error notifications (i.e. a syntax error from trying to execute a query with a typo), all notifications are closed.
If I start another query run before pressing ESC, the (valuable) notification containing the query progress also vanishes, along with the cancel button.
However the query is still executed in the background.

**Describe the solution you'd like**
Pressing ESC once should not close a notification that provides information about a running query.
If possible, pressing ESC twice could close that notification as well.

**Describe alternatives you've considered**
None

**Comment by alexet** [comment]
You should be able get them back after hiding them with `ESC` by clicking the bell icon in the corner. There is no way to get them back after clearing them though but vscode gives no api to know if that has happened.

**Comment by Cornelius-Riemenschneider** [comment]
Ah, I didn't know that ESC was only hiding the notifications, thank you!
That's good enough for me, so I'm closing the issue.
