### ISSUE TITLE
Allow databases to be downloaded via http

### ISSUE THREAD

**Issue by jrozner** [github/vscode-codeql#2324]
Currently the extension won't allow databases to be downloaded over http. The code enforcing that is https://github.com/github/vscode-codeql/blob/d861772eb13e85609ce38b977839440fca6cffeb/extensions/ql-vscode/src/databaseFetcher.ts#L52. Would you be open to removing this entirely or at the very least introducing a config option to allow it? I build and store databases on a remote system on my local network and it's a pain to have to setup tls and key management on my private network.

**Comment by aeisenberg** [comment]
I would recommend that you download and unzip the database from outside of vscode and then import it into vscode as a folder.

**Comment by jrozner** [comment]
Ya, that will work but having to jump through those hoops is really a pain. Is there a reason the check can't just be disabled by the user?

**Comment by aeisenberg** [comment]
I will discuss this internally and put it on our backlog. I can't guarantee that we will move forward with this. If we were to implement, then downloading via http would have to be guarded by a configuration flag.

**Comment by jrozner** [comment]
I think that's a completely reasonable solution. Would you accept a PR? I'm happy to submit one, just not going to spend the time if it's something that would be rejected on principle.
