### ISSUE TITLE
Text in interpreted results view header appears to have slightly different vertical alignment

### ISSUE THREAD

**Issue by henrymercer** [github/vscode-codeql#237]
**Describe the bug**
The various bits of text in the interpreted results view header appear to have very slightly different vertical alignments:

![image](https://user-images.githubusercontent.com/14129055/74434324-226fd900-4e5a-11ea-8835-863148c81c64.png)

Here, the text on the right hand side is the lowest, followed by the text on the right hand side, followed by the text in the centre.

**To Reproduce**
Run a path query, view the query results, and select "alerts" from the dropdown to view the interpreted results. 

**Expected behavior**
The text in the screenshot should have the same vertical alignment.

**Comment by aeisenberg** [comment]
You've got a keen eye. I missed that.
