### ISSUE TITLE
Add setting for disabling caching of IDE contextual queries

### ISSUE THREAD

**Issue by hvitved** [github/vscode-codeql#2378]
Like we have
```
"codeQL.astViewer.disableCache": true
```
today, it would be nice to have similar settings for other contextual queries, e.g. jump-to-definition.

**Comment by aeisenberg** [comment]
I am proposing using `"codeQL.contextualQueries.disableCache": true`. This setting will apply to both jump to def and find refs.

@hvitved do you use the CFG viewer? Do you want there to be a way to avoid the cache here as well? I propose using the same AST viewer setting.

**Comment by hvitved** [comment]
Would certainly make sense to have a similar option for the CFG viewer. Last I tried using the CFG viewer, I ran into a bug, but can't remember which. I'll give it another try.
