### ISSUE TITLE
Set up a linter to standardise code formatting

### ISSUE THREAD

**Issue by henrymercer** [github/vscode-codeql#238]
To save time when reviewing PRs by reducing formatting changes and discrepancies, we should set up a linter or similar to automatically standardise the formatting of our code.

**Comment by jcreedcmu** [comment]
You can add `npm run format`, which runs `tsfmt` to your pre-commit hooks if you want.

**Comment by jcreedcmu** [comment]
I don't have strong feelings about enforcing formatting, I just look at diffs with whitespace changes hidden.

**Comment by jcreedcmu** [comment]
Ah, I see, admittedly `tsfmt` is a bit buggy on `jsx`, which I see now is what prompted this issue. Shrug.

**Comment by aeisenberg** [comment]
eslint and prettier are now the preferred way of linting and formatting typescript. I think it's something worth looking into. I'm less concerned about what the rules are than just that we are enforcing consistency across the project.

https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project

**Comment by aeisenberg** [comment]
OK...my change uses mostly default linting options. It makes a few things slightly more lenient, though there are still lots of small things that need to be fixed. For now, I'm thinking that we don't try to fix everything at once. and only fix a file when you're editing it for some other reason as part of another PR. Eventually, we should get to a point where we can add a lint step to the build process.
