### ISSUE TITLE
Quick eval doesn't save file first

### ISSUE THREAD

**Issue by owen-mc** [github/vscode-codeql#2390]
**Describe the bug**
When I quick eval, if the file has been edited then it isn't saved and the on-disk version is used. This is quite irritating.

**Version**
CodeQL extension version: 1.8.3 
CodeQL CLI version: 2.12.7 
Platform: darwin x64

Version: 1.78.0-insider (Universal)
Commit: 5b6af0748264d83dc7a95f5f4b1c39196eaae8d9
Date: 2023-04-27T23:57:36.064Z (13 hrs ago)
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0
Sandboxed: YesVersion: 1.78.0-insider (Universal)
Commit: 5b6af0748264d83dc7a95f5f4b1c39196eaae8d9
Date: 2023-04-27T23:57:36.064Z (13 hrs ago)
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0
Sandboxed: Yes

**To reproduce**
1. Open a file containing some QL, edit and don't save.
2. Quick eval something in the file
3. The file is not saved, and what is evaluated is based on the version of the file on disk.

**Expected behavior**
The file is saved before the selection is evaluated.

**Additional context**
I looked for relevant settings and the only one I could find was “Code QL › Running Queries: Auto Save”, which is already enabled.

I haven't checked if the same is true for evaluating a query.

**Comment by aschackmull** [comment]
This is extremely annoying.

**Comment by owen-mc** [comment]
I just double-checked and this is indeed fixed. I can stop reflexively saving things before quick-evaluating. Thanks @dbartol !
