### ISSUE TITLE
Timeout during query compilation should produce failed query history item

### ISSUE THREAD

**Issue by henrymercer** [github/vscode-codeql#250]
**Describe the bug**
When query compilation times out, the message `The request (id: 6, method: 'compilation/compileQuery') has been cancelled` is added to the extension log, but a query history item corresponding to the timed out query is _not_ added to the query history view.

**To Reproduce**
1. Set `codeQL.runningQueries.timeout` to 1 second
1. Run a long-running query e.g. a path problem query
1. Focus the query history view
1. Observe that the query history view doesn't contain an item corresponding to the timed-out compilation.

**Expected behavior**
The query history view should contain an item corresponding to the timed-out compilation with a failed icon and the status "timed out".

**Comment by aeisenberg** [comment]
The behaviour you are describing isn't exactly what I'm seeing. The query does seem to be added to the query history page as an error. Though, the message is incorrect. I'm seeing something like:

```cancelled after 0 seconds```

It looks like the cli is incorrectly tagging the query as being cancelled instead of timedout.

**Comment by aeisenberg** [comment]
Is it possible that the incorrect tag is because the timeout is on vscode's side, not the cli? And when the timeout is reached, vscode triggers the cancel in the cli?

**Comment by aeisenberg** [comment]
Oddly though, when I actually try to cancel the query, the result comes out as `QueryResultType.OTHER_ERROR`. Seems like there's a bit of work to do regarding the query statuses.

**Comment by aeisenberg** [comment]
And...now, I'm able to reproduce @henrymercer's original issue. Not exactly sure what's different now.

**Comment by aeisenberg** [comment]
Now, I'm able to reproduce the error described by @henrymercer. Looks like a `UserCancellationException` is being thrown somewhere and it is bubbling up to the wrong place. It needs to be caught earlier and a synthetic result needs to be created and passed to the query history manager.
