### ISSUE TITLE
"Finding definitions" in non-ql files

### ISSUE THREAD

**Issue by am0o0** [github/vscode-codeql#2572]
I have a open issue [here](https://github.com/github/codeql/issues/13254), should I report the issue in this repository?

in CodeQL VScode extension (linux), when I click or just hold Ctrl key on part of the source code of imported DB (src.zip), then codeql will try to resolve the definitions of non-ql files. the problem is that, it takes a lot of time and resources to resolve the files that are not codeql query files.
![image](https://github.com/github/vscode-codeql/assets/77095239/1562400e-261e-4bde-a48e-af8de68b9108)

for reproducing this, I figured out that if you hold Ctrl and point the mouse cursor on these files then you can see the notification on above screenshot.

**Comment by MathiasVP** [comment]
Hi @amammad,

We've created an internal issue for this and we'll let you know as soon as we have an update on this 🙂.

**Comment by aeisenberg** [comment]
Fixed by https://github.com/github/vscode-codeql/pull/2885
