### ISSUE TITLE
Better Auto complete 

### ISSUE THREAD

**Issue by amammad** [github/vscode-codeql#2573]
Hi, it would be great when we are typing predicate/class names during query writing there is a better search algorithm for the auto complete popup, I'm facing following problems everyday:
searching for module/class names after typing a letter  like `::letter` is not same/good like searching algorithm for predicate
sometimes the `.letter` doesn't show any suggestions like when I write a uppercase letter as a first letter search to look for suggestion.(e.g. in picture I want to find `getALocalSource` but there isn't any suggestion for that)
![image](https://github.com/github/vscode-codeql/assets/77095239/65eab98f-c606-4c5e-b26c-73cdc2253424)
typing get will give us `getALocalSource` but the only thing that I know is that I want a predicate with name `Local`
![image](https://github.com/github/vscode-codeql/assets/77095239/5fefcc92-1e6b-4fa8-9f8c-fa06d174706b)
here I can't reach `getALocalSource` after typing `Lo`
![image](https://github.com/github/vscode-codeql/assets/77095239/09e3dfc3-de03-44d7-9598-9cc0a754a3c5)
the module class names are more critical for me some times the `DataFlow::Class` is what I want to start work with it.
![image](https://github.com/github/vscode-codeql/assets/77095239/de8d6e57-d207-4c7d-acf9-5add20887590)
I wanted to search for word State in previous screenshot but I had to try Flow to find it!

I want to search for a predicate with word Source/source in it
![image](https://github.com/github/vscode-codeql/assets/77095239/7aada470-0530-44c4-a79d-998e92890762)
I can't !
![image](https://github.com/github/vscode-codeql/assets/77095239/dcd5af34-0236-455c-8258-34b8640effe7)
but it is popped up now!

**Comment by jbj** [comment]
Thank you for writing up your findings and documenting with screenshots.

@kaspersv is making some adjustments to autocomplete this week, and I think they'll address some of the problems you've raised here, so I've assigned @kaspersv. Let's see at the end of this week what's left and whether it makes sense to create new issues or keep this one.

**Comment by jbj** [comment]
The work is on pause at the moment because of summer holidays.

**Comment by kaspersv** [comment]
Thanks for the improvement suggestion/bug report, @amammad! 

I've merged a change to our language server that switches from server-side prefix filtering of autocomplete suggestions to client-side filtering. When autocompletion is triggered in a context such as `source.Lo` we thus send all possible autocompletions (i.e., independent of the prefix) to the client (VS Code) and let the client handling search & filtering. This should give you the desired autocompletion behaviour. 

The change is scheduled for release with CodeQL v. 2.14.2 around mid-August. 

I will close this issue for now. Feel free to reopen the issue or create a new issue, if the issue has not been fully addressed.
