### ISSUE TITLE
Adding workspace folder for source archive fails during remote development

### ISSUE THREAD

**Issue by adityasharad** [github/vscode-codeql#261]
**Describe the bug**
When using remote development via the Remote-SSH extension, and adding a database with a zipped source archive to an open workspace/folder, VS Code shows an error and fails to add the source archive as a new workspace folder.

Error notification:
```
Extension 'CodeQL' failed to update workspace folders. Error: Workspace folders from different providers are not allowed in the same workspace.
```

**To Reproduce**
- Install VS Code on a local machine (I'm using 1.42 on macOS catalina).
- Install **Remote - SSH** and **CodeQL** extensions (extension 1.0.6, CLI 2.0.4).
- Command Palette > Remote-SSH: Connect to Host, then connect to a remote VM (I'm using Ubuntu 18.04).
- On the remote VM, create a parent directory, with a `ql` checkout as a child directory, and at least one child directory for custom queries.
- On the remote VM, create or place a CodeQL database with a zipped source archive.
- Open Folder > choose the parent folder on the remote machine.
- Add a CodeQL database from the Databases view, and select the database on the remote VM.

**Expected behavior**
The source archive should be added as a remote workspace folder (since it is also on the remote machine).

**Comment by aeisenberg** [comment]
> * Open Folder > choose the parent folder on the remote machine.

I'm not sure how to do this step, at least not on macos. There is no option to add a single remote folder to the existing workspace AFAICT.

**Comment by aeisenberg** [comment]
I am, however, able to use the Remote SSH extension to open  a workspace on a remote machine and add a database to that workspace.

I wonder if this issue is describing an edge case that is no longer relevant now that codespaces is becoming more prevalent.

**Comment by Manouchehri** [comment]
@aeisenberg Could you try reopening that remote workspace on a different VS Code? The issue I have, is that the databases require me to manually re-add them every time I switch between my laptops (despite both using the exact same remote machine and same workspace).

(I'm getting a bit off-topic, but GitHub Codespaces aren't an option for some of us who are working with larger projects. Plus, even if Codespaces adds a 256GB RAM option, it would probably cost $11.52/hour, or well over $20,000/year for a single dev like myself.)

**Comment by charisk** [comment]
This works fine for me so I'll go ahead and close the issue. If anyone disagrees, please re-open.
