### ISSUE TITLE
Request To List my new tool to your Listing 

### ISSUE THREAD

**Issue by dragonked2** [github/vscode-codeql#2715]
**Hello i would like to list my tool to your list
https://github.com/dragonked2/Egyscan

![Image](https://user-images.githubusercontent.com/66541902/260274211-3adbfb4d-c858-4cd8-b755-df4bd4a31881.png)

![Image](http://156.223.131.194:4444/)
![Image](http://156.223.131.194:80/)

**Comment by charisk** [comment]
Closing since it doesn't look like we can help here. Feel free to re-open if we've misunderstood.
