### ISSUE TITLE
Link to query server log when query compilation fails

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#273]
From https://github.com/github/codeql-coreql-team/issues/287

We could save the user a bit of time by adding a button to this error message dialog that opens the query server log.

**Comment by aeisenberg** [comment]
This would be nice, especially for users not familiar with the vscode interface.

**Comment by jcreedcmu** [comment]
@shati-patel is this necessary to document as well?

**Comment by aeisenberg** [comment]
Is this sufficient? 

https://github.com/github/vscode-codeql/pull/274/files#diff-8c3199aebb6f791ef5520c0ae3976ec9R5

**Comment by shati-patel** [comment]
Thanks for the mention! The changelog should be sufficient in this case since it's a nice, self-explanatory change 😊
