### ISSUE TITLE
Updating CodeQL CLI hangs loading the workspace tree

### ISSUE THREAD

**Issue by lcartey** [github/vscode-codeql#283]
**Describe the bug**
When I load VS Code, and there's an update to the CodeQL CLI available, the CLI is automatically downloaded. However, VS Code will not load my workspace tree whilst the CLI is downloading (it's simply blank).

It seems like we're doing the CLI update in some sort of initialization handler which is preventing the workspace tree from loading.

**To Reproduce**
Open VS Code after CodeQL CLI has been updated.

**Expected behavior**
Workspace tree should be available while new CodeQL CLI is downloading.

**Comment by aeisenberg** [comment]
I see what's happening. Looks like when the extension starts, there is an automatic check for an update. If there is one, then the update starts downloading whether you want it to or not. There is also a manual way to check for an update, which does not require workspace lock. Though, it does require a restart.

Seems to me that the second approach is better in this case even on startup. The approach would be:

1. on startup, check for update
2. if there is one, ask user if it should be downloaded
3. download in background if requestsed
4. ask to restart when complete

@jcreedcmu, is there any historical reason why this is not a good approach?
