### ISSUE TITLE
Quick evaluation in `.qll` files fails

### ISSUE THREAD

**Issue by max-schaefer** [github/vscode-codeql#293]
**Describe the bug**

Quick-evaluating an expression in a `.qll` file fails with 'The selected resource is not a CodeQL query file; It should have the extension ".ql".' It works in a `.ql` file.

**To Reproduce**
1. Select a JavaScript database
2. Open the JavaScript library `Expr.qll` from latest `master` on `Semmle/ql` (any other `.qll` file should work as well)
3. Try to quick-evaluate the predicate `ExprOrType::getEnclosingStmt`
4. Get an error saying 'The selected resource is not a CodeQL query file; It should have the extension ".ql".'

The above reproduction steps use JavaScript as an example, but the same happens in other languages.

**Expected behavior**
The expression should be evaluated.

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 18.04.4)
 - Version: CodeQL 1.1.0

**Additional context**
This problem seems to be new in CodeQL 1.1.0.

**Comment by jcreedcmu** [comment]
Ah, yes, I should have caught this in review. Fix incoming.

**Comment by jcreedcmu** [comment]
@max-schaefer we'll make a bugfix release soon but you can manually install the dev build of the extension in https://github.com/github/vscode-codeql/actions/runs/58361000 if you want.

**Comment by max-schaefer** [comment]
Great, thanks for fixing this so quickly! (For now I've worked around this by modifying the extension in situ.)
