### ISSUE TITLE
Error running query: Pending response rejected since connection got disposed (codeQL.runQueryContextEditor)

### ISSUE THREAD

**Issue by Sim4n6** [github/vscode-codeql#2973]
# Describe the bug
Well, I have a set up as follows:
- Digital Ocean instance connected using remote SSH VSCode extension.
- in the instance, there is a a CodeQL cli installed.
- codeql created a database in the instance. 
- wanna run a query from my machine (client) via Remote SSH VSCode to the instance so that the computation is performed in the DO instance.

# Version
- CodeQL extension version: 1.9.2 
CodeQL CLI version: 2.15.0 
Platform: linux x64

# To reproduce
reproduce a similar setup and try to run QL query.

**Expected behavior**
You would get the following error each time

```
Error running query: Pending response rejected since connection got disposed (codeQL.runQueryContextEditor)
```

# Additional context

I am willing to provide details right away this weekend and the starting of the next week

**Comment by Sim4n6** [comment]
Can this be related to an unstable internet connexion?

**Comment by charisk** [comment]
Hi @Sim4n6, thanks for filing a bug!

> Can this be related to an unstable internet connection?

Possibly.. Does the issue come up all the time or is it transient? 

I've tested the flow in a Codespace which uses remote host functionality and I was able to run a CodeQL query successfully, but that doesn't exactly replicate your setup

In general, it seems like we have a couple of issues around working with a remote host so I'm not sure of the state of things:
- https://github.com/github/vscode-codeql/issues/261
- https://github.com/github/vscode-codeql/issues/460

I'll discuss a bit with the team and come back to you.

**Comment by Sim4n6** [comment]
Go query was run successfully one time in the remote setup previously mentioned. The ruby query run failed twice. 
I thought it was because, during the query running, I fired a local terminal ssh connection to the same instance.... I am still investigating on my side.

**Comment by Sim4n6** [comment]
It is definitely related to some limiting factor either instance CPU overload or instance bandwidth limitation. 

Check this case in Github Codespace:

<img width="960" alt="Capture d'écran 2023-10-17 181457" src="https://github.com/github/vscode-codeql/assets/13036531/f90ad4ac-d9c0-4cc6-be69-c4827bfceba1">

**Comment by charisk** [comment]
Thanks for the info! It does seem to be related to CPU/bandwidth. Are you running a particularly complex query?

I've tried to reproduce this (using a basic Azure VM) and generally the extension was generally working okay, however at some point I ran a problem query against the linux kernel database and I saw the same error as you. The CPU was at 90+%

**Comment by Sim4n6** [comment]
The query fails.more often when the source equals any(dataflow node).

**Comment by charisk** [comment]
@Sim4n6 have you tried running any of these queries locally at all rather than through a remote host?

**Comment by Sim4n6** [comment]
Well, the point of using a remote instance is to circumvent my little laptop perf. The syntax is correct for sure.

**Comment by Sim4n6** [comment]
I would share the query... In an hour please.

**Comment by charisk** [comment]
> Well, the point of using a remote instance is to circumvent my little laptop perf. The query syntax is correct for sure.

Make sense!

To give you a bit more context, I'm wondering if something specific to the query/database is hitting a CodeQL performance issue/edge case - that will help us clarify whether this is a CodeQL issue or a VS Code extension issue. 



> I would share the query... In an hour please. 

Thank you. If you don't want the query to be public, feel free to DM me in the [Security Lab Slack instance](https://ghsecuritylab.slack.com/signup#/domain-signup).

**Comment by Sim4n6** [comment]
It is this ruby ql query https://github.com/github/codeql/pull/12992/files#diff-8c993937eef8b8df6969f780265e623d0231fa9c9e1d819f0c66ab9ccc984e89

On a database generated from https://github.com/shirasagi/shirasagi commit f249ce3f06f6bfbc0017b38f5c13de424334c3ea

The source is set to `any(DataFlow::Node n) and state ...`

PS: I remain available for further details.

**Comment by MathiasVP** [comment]
> The source is set to `any(DataFlow::Node n) and state ...`

That is most likely what's going wrong. Setting your source to be any node in the database will never work on any database larger than a "hello world" project.

So you need to restrict your `isSource` somehow. You can read more about how to write a dataflow query at https://codeql.github.com/docs/codeql-language-guides/analyzing-data-flow-in-ruby/#.

**Comment by Sim4n6** [comment]
But on a laptop with 16G RAM, the query works ... I should definitely avoid that use.

**Comment by Sim4n6** [comment]
Thank you very much.

**Comment by charisk** [comment]
Are you happy for us to close the issue @Sim4n6 ?

**Comment by Sim4n6** [comment]
sure, no problem.
