### ISSUE TITLE
Showing log associated to query should work for large query logs

### ISSUE THREAD

**Issue by jcreedcmu** [github/vscode-codeql#301]
@tausbn reported being unable to view ~448M query log file from the query history, with the only message being that arising from
```
helpers.showAndLogErrorMessage(`Could not open log file ${queryHistoryItem.logFileLocation}`);
```
in `query-history.ts`. He says when he tried to open the same file manually, it worked. We should probably at least log the exception being handled, and if possible, show the log in some way, even if it's without syntax highlighting.

**Comment by aeisenberg** [comment]
I just created a 2.5G query log file and opened it through the query history. The file opened with no errors. And the editor is surprisingly responsive. Something else must have been going on with the error reported above.

**Comment by aeisenberg** [comment]
OK...reproduced.
