### ISSUE TITLE
mac m1 view AST 报错

### ISSUE THREAD

**Issue by Asiaforest** [github/vscode-codeql#3080]
![image](https://github.com/github/vscode-codeql/assets/61967871/515dd8a3-9089-4972-9825-1a88d4692b57)

**Comment by norascheuch** [comment]
Thanks for opening an issue! Unfortunately, this doesn't contain enough information for us to debug the problem, so I'll close this for now. To report a bug, please use the "bug report" issue template and provide the necessary information.
