### ISSUE TITLE
New tests not discovered within the current workspace without restart

### ISSUE THREAD

**Issue by adityasharad** [github/vscode-codeql#310]
**Describe the bug**
When a new CodeQL test case/directory is added within an existing workspace, it is not visible in the Test Explorer until the workspace is closed and reopened.

**To Reproduce**
1. Add a workspace folder with existing test cases, e.g. a checkout of `Semmle/ql`
1. Duplicate a directory of test cases, e.g. copy `ql/java/ql/test/dataflow/taint-ioutils` to `ql/java/ql/test/dataflow/taint-ioutils2`.
1. Go to the Test Explorer view. The new test directory is not visible in the UI, and so cannot be run on its own. However, running the tests in a parent directory will pick up the new test cases.

**Expected behavior**
The new test directory is visible in the Test Explorer UI, and can be run directly.

**Additional context**
CodeQL for VS Code 1.1.1, Test Explorer UI 2.17.0, VS Code 1.42.1.

**Comment by tausbn** [comment]
> 3\. ... However, running the tests in a parent directory will pick up the new test cases.

This did not work for me. Closing and reopening the workspace did, however.

**Comment by aeisenberg** [comment]
This is working for me. Closing the issue and we can revisit if anyone is still experiencing the problem.
