### ISSUE TITLE
Database download gets stuck on connection issues

### ISSUE THREAD

**Issue by Marcono1234** [github/vscode-codeql#3204]
**Describe the bug**
When a network connection issue occurs while downloading a database (from GitHub), the download just gets stuck. No error is reported, nothing is logged and when the network connection is restored the download does not continue either.

Possibly related to #903

**Version**
Extension:
```
CodeQL extension version: 1.11.0 
CodeQL CLI version: 2.15.5 
Platform: win32 x64
```

VS Code:
```
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

**To reproduce**
1. Start the download of a large CodeQL database, for example the Java database for https://github.com/elastic/elasticsearch (~300 MB)
2. While the download is in progress, disconnect from the internet
3. Wait some time, optionally reconnect to the internet
:x: Bug: Nothing happens, the download progress notification is stuck

**Expected behavior**
Either:
- The download should fail and an error should be reported
- Or, a warning or error should be shown / logged and the download should continue once the internet connection is restored

**Comment by jf205** [comment]
Thanks @Marcono1234. I think we can do a better job with the UX in this case. You may be right that it is related to https://github.com/github/vscode-codeql/issues/903. We will discuss and get back to you.
