### ISSUE TITLE
Add ability to sort databases alphabetically and chronologically

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#322]
This is a subtask of #318.

Chronologically by time added or time created?

**Comment by adityasharad** [comment]
> Chronologically by time added or time created?

Time added to the workspace sounds like a good way to start.

**Comment by aeisenberg** [comment]
Unfortunately, there is no easy way to get time added to the workspace. It's a field that we will have start adding to new databases. So, can't retroactively apply it. I'll first add sort by name. And then consider how to add another kind of sorting.
