### ISSUE TITLE
Provide basic XML syntax highlighting for qhelp files

### ISSUE THREAD

**Issue by p-** [github/vscode-codeql#325]
**Problem**
As a developer it would be nice to have basic syntax highlighting support for qhelp files.
Currently qhelp files are displayed as plain text and look rather dull ;)
Also there's no help for finding out which tags belong together.

**Proposed solution**
Since qhelp files are basically XML files interpreting them as XML files would be a low hanging fruit.
This would not automatically XML validation support as VS code does not support XML validation out of the box.

**Describe alternatives you've considered**
An alternative would be to use a different VSCode grammar set that restricts the set of tags that can be used. However, I think that would be a better candidate for XML validation.

**Additional context**
I will create a small pull request for this issue.
The Pull request instructions instructed me that issues need to be created for any UI or other user-facing changes, so I created this one.

**Comment by aeisenberg** [comment]
Closed by #326.
