### ISSUE TITLE
No syntax highlighting for `unique` aggregate

### ISSUE THREAD

**Issue by dbartol** [github/vscode-codeql#329]
**Describe the bug**
The QL text `unique` is highlighted as a predicate or variable name, not a keyword

**To Reproduce**
Open a query that uses the `unique` aggregate in the editor.

**Expected behavior**
The `unique` identifier is highlighted as a keyword.

**Additional context**
OK, `unique` is technically not a keyword, since it's context-sensitive, but it should look like one when used as an aggregate name.

**Comment by dbartol** [comment]
@github/product-docs-dsp CC'ing you as instructed in the issue template, but I don't think this needs any doc changes beyond the changelog entry I already made.

**Comment by shati-patel** [comment]
> @github/product-docs-dsp CC'ing you as instructed in the issue template, but I don't think this needs any doc changes beyond the changelog entry I already made.

Thanks for the ping! You're right, the changelog entry is enough ⚡
