### ISSUE TITLE
In test diffs, compare the result to an empty file if no .expected file exists

### ISSUE THREAD

**Issue by rdmarsh2** [github/vscode-codeql#338]
**Is your feature request related to a problem? Please describe.**
After creating a new test (with source and query, but no `.expected` file) and running a test through the test explorer, the "show test output differences" menu item fails with `Error: unable to resolve non-existing file`.

**Describe the solution you'd like**
The "Show test output differences" menu item opens a diff window in which the `.actual` file is compared to an empty file. It might also display a warning message.

**Describe alternatives you've considered**
The menu item could instead open the `.actual` file itself, possibly while displaying a warning message.

**Comment by aeisenberg** [comment]
Would it be sufficient to create an empty expected file and run the diff command as normal (and pop up a warning)?

Then you could easily copy over the `actual` file into the `expected`.

**Comment by rdmarsh2** [comment]
Yeah, that would work. It looks like what we currently do for an expected file without an actual file is to just open the expected file, which would make it easy to see the results, but might be a bit confusing.
