### ISSUE TITLE
Consider unpacking source archives to filesystem

### ISSUE THREAD

**Issue by jcreedcmu** [github/vscode-codeql#341]
Here's a user report of someone wanting to using `vscode-codeql` together with `vscode-ccls`, a  C/C++/Objective-C language server and code navigation tool: https://twitter.com/esizkur/status/1254550437568679937

The use case is: the user has a snapshot with a `.zip`ed source archive. They run a CodeQL query, which has some results. They click on one of the results, which opens a buffer in vscode showing source file inside the zipped source archive. At the moment, it's not the case that this is a real file in the actual filesystem; we're using [FileSystemProvider](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider) to directly slurp the file out of the `.zip` archive. This means that `ccls`, which only supports `file:///` urls, doesn't know how to index and navigate the source archive.

What we could do instead of all of this virtual filesystem dance is as-needed unpack the .zip somewhere (into workspace-local storage?) and have `file:///` urls pointing into that location. Possible downsides include: latency for the first such file shown is the cost of unpacking the whole archive, cost of disk from unpacking it, and exposing the implementation details of where we're storing files, possibly making it harder to change implementations later if users depend on that.

**Comment by MartijnB** [comment]
An potential (and maybe simpler) alternative to unpacking the source archive might be to check if it is possible to open the original source file. The database contains the metadata file that contains sourceLocationPrefix, If this method is preferred over opening the file from the zip archive when possible, this likely would solve the issue.

**Comment by jcreedcmu** [comment]
Had some discussion about this offline. Because we depend on a zip archive existing for other mechanisms (such as mapping from opened source archive files to the database they come from) this seems redundant or conflicting with this choice. Closing until we have a stronger motivation for this sort of redesign.
