### ISSUE TITLE
Feature request: Export query results (as SARIF/CSV)

### ISSUE THREAD

**Issue by jcreedcmu** [github/vscode-codeql#342]
After a query is run, we should allow exporting the results as a SARIF file --- in the implementation, this will actually be nearly trivial, as we already use the codeql cli to create a SARIF file during interpretation, and store it in a workspace-local state directory. A solution could simply be to provide a way of conveniently opening this file within vscode (from the query history view, or from the results panel) after which point the user can save it wherever they like.

Also consider exporting as CSV for parity with the eclipse plugin.

- [x] SARIF
- [x] CSV

**Comment by rajatdiptabiswas** [comment]
Would you kindly let me know what exactly needs to be done so that I can try working on this?
Please mention anything I should read on or know about before starting this. It will help out a lot.

Thanks in advance!

**Comment by jcreedcmu** [comment]
Thanks for offering to contribute! I'll try to explain in a bit more detail.

The function [interpretBqrs](https://github.com/github/vscode-codeql/blob/master/extensions/ql-vscode/src/cli.ts#L513) reads in a bqrs (binary query result set) file and produces a SARIF file. We want the user to be able to view and save this file elsewhere if they want, when a query is finished running. The place in the filesystem where that SARIF file is stored is already chosen and passed down there, if we look up the stack at callers of interpretBqrs, which are [interpretResults](https://github.com/github/vscode-codeql/blob/master/extensions/ql-vscode/src/query-results.ts#L151) and [getTruncatedResults](https://github.com/github/vscode-codeql/blob/master/extensions/ql-vscode/src/interface.ts#L387) and in [interpretResultsInfo](https://github.com/github/vscode-codeql/blob/master/extensions/ql-vscode/src/interface.ts#L443). So there we see `query.resultsPaths` has the appropriate paths for a `query` object of type `QueryInfo`.

One thing that could be done is, for an item in the query history (a thing of type [CompletedQuery](https://github.com/github/vscode-codeql/blob/master/extensions/ql-vscode/src/query-results.ts#L12)) add a context menu command "Show SARIF Results" which requests vscode open the file that corresponds to the interpreted results path of the query of the query history item that you had selected. If you need any pointers to vscode api internals, or to examples of other context commands in the extension source, lmk!

**Comment by rajatdiptabiswas** [comment]
Seems a bit complicated but I'll try my best.
I have an exam coming up, but I shall try to get it done as soon as possible.

I'll let you know if I run into any issues!

**Comment by rajatdiptabiswas** [comment]
Hi @jcreedcmu, I think it would be best if someone else looked into this issue.
You've done a great job at explaining but I won't be able to give time to this at the moment.

I have looked into the project files and it will take me some considerable time to solve this because I haven't worked on VS Code extension development before.

Wishing whoever takes on the issue good luck!

**Comment by jcreedcmu** [comment]
No problem, thanks for giving it a look!

**Comment by chen965** [comment]
qqqq
