### ISSUE TITLE
Support for source locations provided by `getURL`

### ISSUE THREAD

**Issue by max-schaefer** [github/vscode-codeql#348]
**Is your feature request related to a problem? Please describe.**
The help topic on [Locations and strings for QL entities](https://help.semmle.com/QL/learn-ql/locations.html#providing-urls) describes how a `getURL` predicate can be used to provide a source location for a QL entity.

As a contrived example, the following query selects all addition expressions in a JavaScript database, but with their source locations shifted to the right by one character:

```ql
import javascript

class ShiftedAddExpr extends AddExpr {
  string getURL() {
    exists(string filepath, int startline, int startcolumn, int endline, int endcolumn |
      getLocation().hasLocationInfo(filepath, startline, startcolumn, endline, endcolumn) and
      result =
        "file://" + filepath + ":" + startline + ":" + (startcolumn + 1) + ":" + endline + ":" +
          (endcolumn + 1)
    )
  }
}

select any(ShiftedAddExpr a)
```

This works in the legacy QL-for-Eclipse plugin, but in the VSCode extension the results end up not being clickable.

**Describe the solution you'd like**
In the interest of feature completeness, it would be great if source locations provided by `getURL` work.

**Comment by aeisenberg** [comment]
I see where the problem is. Our bqrs results parser is only able to convert string locations into whole file urls. I think I can augment this a bit and allow for string locations directly into files.

**Comment by aeisenberg** [comment]
@max-schaefer I see you have added `+ 1` to the start and end column. Is that a requirement? I'm guessing this is because BQRS expects a one-based offset, but `getLocation()` produces a 0-based offset?

Just want to confirm before committing anything.

**Comment by max-schaefer** [comment]
Ah, no, that's just part of the example. When testing in Eclipse I wanted to make sure that I was actually seeing the result of `getURL` rather than the normal location provided by `hasLocationInfo`, so I made `getURL` shift the location to the right by one character.

**Comment by aeisenberg** [comment]
Thanks for the clarification. Then #353 is correct as it is.
