### ISSUE TITLE
Feature request: allow to limit results by path length in UI

### ISSUE THREAD

**Issue by p-** [github/vscode-codeql#3660]
**Is your feature request related to a problem? Please describe.**

When using MRVA with a query (custom or default) that yields a lot of results it is often hard to figure out which of the results are the most promising ones. See also: [Feature request: Display length of shortest path in UI](https://github.com/github/vscode-codeql/issues/3659). 
Currently there's no (simple) feature in CodeQL to limit query results by max path lengths, so this has to be done in the result viewer or by filtering the Sarif files.
It would be nice to filter out all results that have paths that are longer than a certain number. This number should be freely selectable as sensible values depend on the query and the language (e.g. Java is known as a more verbose language and has often longer code paths).

**Describe the solution you'd like**

It would be nice if there was a filter option (e.g. called "max path length") to filter out results with a path length that is over a certain value (For MRVA and maybe also for local queries).

I've hacked this together in my [experimental branch](https://github.com/p-/vscode-codeql/tree/p--max-path-steps) and it's already useful - see commit https://github.com/p-/vscode-codeql/commit/7f6f9c98f9bd5ffd0a222045d1c9225cf61da7a2

![Image](https://github.com/user-attachments/assets/f5da189b-8903-47b9-a63e-a4274a6fc0f9)

**Additional context**

See also: [Feature request: Display length of shortest path in UI](https://github.com/github/vscode-codeql/issues/3659)

**Comment by jf205** [comment]
Hi @p-! Thanks for creating this issue, we appreciate the thought you've put into it. I think we need to give this kind of UI change quite a bit more thought to ensure that it is clear to users, so we won't be adding this functionality at the moment. Please keep providing your feedback though ⚡
