### ISSUE TITLE
Less obtrusive way to ask users to collect telemetry

### ISSUE THREAD

**Issue by isidorn** [github/vscode-codeql#3672]
Hi VS Code PM Here 👋 

1. Install CodeQl
3. See telemetry dialog 🐛 

Here are our telemetry collection guidelines https://code.visualstudio.com/api/extension-guides/telemetry

Based on that I strongly suggest that you do not show this dialog, but instead just respect the respect the `isTelemetryEnabled` and `onDidChangeTelemetryEnabled` from the vscode API. That will make a much smoother user experience, and the user just has to disable telemetry once in vscode and all the extensions will respect that. Thanks

![Image](https://github.com/user-attachments/assets/cf331495-0dec-41a0-8f4e-9776f2f72056)

fyi @TylerLeonhardt

**Comment by jf205** [comment]
Hi @isidorn 

Thanks for creating this issue and for the recommendation. I'll discuss this change with the team.

**Comment by jf205** [comment]
Discussed with the team: we agree that we should respect the `isTelemetryEnabled` and `onDidChangeTelemetryEnabled` from the vscode API. Currently unsure what size effort this would be and therefore also unsure when we'll be able to pick it up.

**Comment by isidorn** [comment]
Thanks for discussing. I do not think this should be a large investment.

**Comment by stonish** [comment]
@isidorn We discussed this a little further as a team, we're onboard with making this change but it's not something that we think we can tackle right now. Even though the investment shouldn't be too large, we're working towards some tight deadlines for shipping new features at Universe and can't take on anything else unless absolutely necessary.

I'm going to set this up for us to revisit it after Universe when I expect we'll have more capacity to take this on. If you think this is a mistake, please let me know and/or re-add this issue to our team board to be re-triaged

**Comment by isidorn** [comment]
Post Universe makes sense. Thank you!
