### ISSUE TITLE
Improve ease of selecting a database on the filesystem

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#383]
https://github.com/github/codeql-coreql-team/issues/70

Slightly confusing that a database is a folder that can be navigated deeper into.

We could allow the user to select the (suitably renamed) `.dbinfo` file instead.

**Comment by aeisenberg** [comment]
I think the easiest and most useful thing to do here is to apply the following heuristics:

1. If the selected URI to add is a file, choose the containing directory
2. If the selected URI is a directory matching `db-*`, choose the containing directory
3. choose the current directory

This will allow someone to select the deeply nested `.dbscheme` file, or the `.dbinfo` file, or any number of other sibling files. Being liberal in what we accept here is not dangerous to the user.

**Comment by dbartol** [comment]
https://code.visualstudio.com/api/references/vscode-api#OpenDialogOptions claims that allowing the dialog to open both files and folders doesn’t work on Windows.
Is there a specific file extension we can filter on?

**Comment by aeisenberg** [comment]
Currently, we specify that only folders can be opened. So, it's not technically possible at this point for a user to select the `.dbscheme` file, but it is still possible for the user to select the `db-*` folder. So, there really is no file extension we can use. The only feature is that if someone accidentally chooses the `db-*` folder, the extension should handle that.

So, I'll just leave #1 unimplemented since it's not possible.
