### ISSUE TITLE
View and Compare DIL in VS Code

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#395]
Ensure that VSCode can view the Datalog Intermediary Language (DIL) of a query with reasonable syntax highlighting and formatting. It's likely that showing this readonly will be fine for our purposes.

Also, would be nice to see a comparison view as well, though likely, this can be delegated to VS Code's standard comparison editor.

**Comment by jcreedcmu** [comment]
@adityasharad didn't have a branch in which you basically implemented this already? Could you post it here?

**Comment by adityasharad** [comment]
@jcreedcmu https://github.com/adityasharad/vscode-codeql/tree/view-dil. Fairly simple implementation for now and needs a rebase.

**Comment by aeisenberg** [comment]
#612 adds a command to view the DIL. Comparison is not directly implemented, though it is possible for users to compare two editors. Maybe this is sufficient.
