### ISSUE TITLE
Add editor problem when `select` or `query` predicate columns do not match with the `@kind` metadata

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#397]
QL4E and LGTM both support checking that the file's metadata aligns with the select or query predicates defined in the file.

This is a language server concern and should be implemented there.

**Comment by cklin** [comment]
This bug should be fixed in the next CodeQL CLI release.

**Comment by cklin** [comment]
This bug has been fixed in CodeQL CLI 2.14.2.
