### ISSUE TITLE
Automate `codeql database cleanup`

### ISSUE THREAD

**Issue by jcreedcmu** [github/vscode-codeql#409]
For the extension to recognize that source files belong to a database's source archive, we currently require that the source archived is a `.zip` archive, as opposed to a `src/` directory. This requirement is satisfied already by databases created with the cli tools, but LGTM still produces databases with `odasa` with unpacked `src/` directories. So the experience the user has when they download a database from `lgtm.com` is that they have to run `codeql database cleanup` to `zip` the source archive before, e.g., jump-to-definition will work.

Some options available are:

1. Simply provide a convenience command in the extension to run `cleanup` on a given database.
2. Prompt the user to ask whether they want to run `cleanup` (though possibly with the question phrased in a more perspicuous way) when a database with unpacked `src/` is added to the workspace.
3. Prompt the user to ask whether they want to run `cleanup` when running a query.

We almost surely don't want to silently do the `cleanup` --- we have deliberately avoided doing any other in-place changes to user databases without notification or offering the ability to decline it.

**Comment by jcreedcmu** [comment]
@shati-patel made the point elsewhere that the 'convenience' even of option 1 is not insignificant, since the user would otherwise need to think about installing the codeql cli themselves, or else figure out where the extension-managed copy is.

**Comment by hmakholm** [comment]
How would the work of this compare to supporting non-compressed source directories?

**Comment by aeisenberg** [comment]
Now that we support importing directly from LGTM, we could perform this cleanup as part of the import process. I think in this case it would be fine to do it automatically, since the db is meant to be completely controlled by the extension.

**Comment by jcreedcmu** [comment]
It's definitely considerably easier to provide definitions/references for urls in the vscode workspace that we control --- otherwise I think we'd have to register/unregister providers based on paths every time we added a directory, instead of the easy thing we're doing now of just registering one provider for the custom url scheme we're using.

We could however imagine keeping the custom url scheme but just mirroring the filesystem directly when it's already unpacked. Maybe that wouldn't be too hard, if I'm not forgetting any other downsides of doing it that way...

**Comment by aeisenberg** [comment]
I think this task is now no longer relevant, at least for databases installed from within the extension. We are automatically zipping the src archive.
