### ISSUE TITLE
Quick-eval of abstract predicate fails

### ISSUE THREAD

**Issue by hvitved** [github/vscode-codeql#412]
**Describe the bug**
When I attempt to quick-eval the abstract predicate `getADynamicTargetInCallContext` in VSCode I get a `The selection is not a valid quick-eval target` error.

**To Reproduce**
Checkout my branch [quick-eval-abstract](https://github.com/hvitved/ql/tree/quick-eval-abstract) and quick-eval [getADynamicTargetInCallContext](https://github.com/hvitved/ql/blob/quick-eval-abstract/csharp/ql/src/semmle/code/csharp/dispatch/Dispatch.qll#L286).

**Expected behavior**
The same as if I had written a query that invoked the predicate.

**Comment by jcreedcmu** [comment]
You do still have the ability to quick-eval other predicates, though? If so, I think the fix will have to be in the queryserver.

**Comment by hvitved** [comment]
Yes, quick-evaling for example one of the overrides works.

**Comment by alexet** [comment]
This is now fixed in the master version of CodeQL and should be included in the release in mid-june.

**Comment by aeisenberg** [comment]
@alexet do you know which CLI version this will be available in?

**Comment by aeisenberg** [comment]
This is now available in production.
