### ISSUE TITLE
Removing leading whitespace when pasting code

### ISSUE THREAD

**Issue by RasmusWL** [github/vscode-codeql#428]
**Describe the bug**
My CodeQL VSCode extension is removing leading whitespace when pasting code into ql/qll files :confused: Pressing CTRL-Z brings back the leading-whitespace to my pasted code.

**To Reproduce**
Paste some QL code into a `.ql` or `.qll` file, for example.

```
predicate foo() {
  none()
}
```

What will actually be pasted is

```
predicate foo() {
none()
}
```

**Expected behavior**
My code gets pasted as is

**Additional context**

- I'm using extension version 1.2.1 with locally compiled codeql binary (which I just rebuild from newest master). I disabled all other extensions in VSCode (just to be sure), and restarted VSCode as well. 
- Manually changing my installed version to 1.2.0 resolves this problem. 
- I'm running Ubuntu 18.04 if that helps any.

**Comment by jcreedcmu** [comment]
I can repro that there is strange indentation behavior, except that I get _extra_ indentation:
```
predicate foo() {
    none()
  }
```

**Comment by RasmusWL** [comment]
Oh, that might be because I'm using a standard tab-size of 4 spaces for QL code (since we still haven't made the move for Python).

**Comment by aeisenberg** [comment]
I can reproduce this. When I change the following setting to `advanced` (default is `full`), the paste behaves as I expect it to.

    "editor.autoIndent": "advanced"

The difference between advanced and full is that full will "honor indentation rules defined by the language". This implies that the indentation rules are being applied incorrectly.
