### ISSUE TITLE
Large zip import fails with 'unexpected end of file'

### ISSUE THREAD

**Issue by jbj** [github/vscode-codeql#436]
**Describe the bug**
Importing a large database from a zip file fails with 'unexpected end of file'.

**To Reproduce**

1. Download the C++ database from https://lgtm.com/projects/g/frederik-h/gcc-lgtm/ci/#ql.
2. In the extension CodeQL pane, click the 'Choose Database from Archive' icon.
3. Choose the zip file you just downloaded.
4. Wait for a moment, and you'll see the error.

It works fine to unzip the file with `unzip` and import it to VSCode via the 'Choose Database from Folder' icon.

**Additional context**
The zip file size is 2,505,687,657. That's over 2^31 - 1, so it's possible that some part of the unzipping library uses a signed `int` for counting bytes.

Using CodeQL for VSCode 1.2.2 in VSCode OSS 1.45.1 on Arch Linux.

**Comment by aeisenberg** [comment]
That's a large one. I'll try this out.

**Comment by aeisenberg** [comment]
Looks to be related to the unzipper library. Filed a bug there: https://github.com/ZJONSSON/node-unzipper/issues/202

I'll keep looking to see if there is another library we can use or else if this is a node issue.

**Comment by aeisenberg** [comment]
I can reproduce the error when I call `node-unzipper` directly to unzip the file. However, when I use the `node-stream-zip` package instead, I can unzip with no problems. Unless the bug in `node-unzipper` can be fixed, I will have to change libraries.
