### ISSUE TITLE
Use locale-aware date formatting for date labels

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#440]
Date labels in the query history not respect the user’s system locale.

**Comment by aeisenberg** [comment]
There are two parts to this problem:

1. First a user must explicitly install the desired locale (vscode will use US English as default) through the _Configure Display Language_ command
2. Then wherever the extension does locale-specific tasks (eg- comparisons or formatting), the current `vscode.env.language` value must be used.

About to put up a PR that adds locale in the proper places.

**Comment by aschackmull** [comment]
Step 1 puts my VSCode in `[Unsupported]` state.  Cf. https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported

**Comment by aschackmull** [comment]
(Fixed by restarting VSCode two times.)
