### ISSUE TITLE
Add a CodeLens for allowing users to run quick eval

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#446]
**Is your feature request related to a problem? Please describe.**

Quick eval is an extremely useful debugging tool, but it is hidden for new users. The idea here is to make this feature more easily discoverable.

**Describe the solution you'd like**

Use the vscode [CodeLens feature](https://code.visualstudio.com/api/references/vscode-api#CodeLensProvider). We would annotate all query predicates and allow easy running of quick eval for parts of the QL file.

**Comment by aeisenberg** [comment]
We need to update the LSP server in order for this to work.

**Comment by adityasharad** [comment]
Code Action rather than Code Lens?

**Comment by shati-patel** [comment]
Done in #1035!
