### ISSUE TITLE
Document how to use VS Code Remote Development to build queries on a remote machine

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#460]
@adityasharad mentioned that it is possible to use VS Code Remote Development to build queries on a remote machine. Let's create some documentation on this. I'm not sure exactly where this should go. Perhaps in the official CodeQL documentation area. Perhaps as a blog post (or both).

First, let's get the documentation down and then let's figure out where it should go.

**Comment by Manouchehri** [comment]
Is there any limitations or catches when using VS Code Remote Development with CodeQL?
