### ISSUE TITLE
Loading databases in directories named `db-*` fails with error 'does not contain a CodeQL dbscheme'

### ISSUE THREAD

**Issue by smowton** [github/vscode-codeql#482]
**Describe the bug**
Loading databases in directories named `db-*` fails with error 'does not contain a CodeQL dbscheme'

**To Reproduce**
Find any old CodeQL database, verify you can load it with the plugin's "Choose database from folder" GUI. Copy it to `/tmp/db-test`, try to load it from there.

You should get an error `Database '/tmp' does not contain a CodeQL dbscheme under '/tmp/db-test'.`

**Expected behavior**
Loading should succeed

Looks like this glob is at fault for misidentifying the database root as a `db-$langname` dataset stored within it: https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/src/databases.ts#L88

**Comment by aeisenberg** [comment]
Thanks for raising this issue. We’ll take a look shortly.
