### ISSUE TITLE
Extension seems to load extra qlpacks

### ISSUE THREAD

**Issue by alexet** [github/vscode-codeql#499]
When resolving qlpacks for tests we seem to resolve more than we should. Judging by the search logs we seem to be adding the home directory to the search path. The command printed in the log wont run for me so I think something is wrong with the log printing. Running without the spurious `--search-path` argument gives a correct result that doesn't match with what is shown so I presume the missing argument is to blame.

**Comment by aeisenberg** [comment]
Simple fix, I think. we have the line `searchPath !== undefined`. It should be `searchPath !== undefined && searchPath.length > 0`.

Or more succinctly: `searchPath?.length`.
