### ISSUE TITLE
Duplicated tests in test explorer view

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#517]
**Describe the bug**

When opening the test explorer in a mult-root workspace, each root contains a copy of all tests available in the workspace.

**To Reproduce**

1. Open vscode starter workspace
1. Open test explorer view
1. Refresh
1. Expand any two root folders

Notice that the two roots have duplicated sub-folders.

<img width="359" alt="_Extension_Development_Host__-_LocalVariableHidesGlobalVariable_qlref_—_vscode-codeql-starter__Workspace_" src="https://user-images.githubusercontent.com/363559/88431313-e9e00e00-cdae-11ea-8deb-5d30652c0fab.png">

**Expected behavior**

Sub-folders should not be duplicated across workspace roots.

**Additional context**

There might be a way to think of this as a feature, not a bug. It might be the case that tests run in the context of different workspace roots will behave differently, so _maybe_ we want to allow this duplication.

**Comment by aeisenberg** [comment]
I think this has to do with qlpack discovery. The extension first does a qlpack discovery on each workspace folder, and then it passes all the discovered qlpacks to the qltest discovery. However, the qlpack discovery returns many qlpacks that are outside the scope of the current directory. 

Here is the command that the extension is issuing, but run on the command line:

```bash
$ ./codeql resolve qlpacks --additional-packs '/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/codeql-custom-queries-cpp'
codeql-cpp (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/cpp/ql/src)
codeql-cpp-tests (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/cpp/ql/test)
codeql-cpp-upgrades (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/cpp/upgrades)
codeql-csharp (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/csharp/ql/src)
codeql-csharp-tests (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/csharp/ql/test)
codeql-csharp-upgrades (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/csharp/upgrades)
codeql-custom-queries-cpp (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/codeql-custom-queries-cpp)
codeql-custom-queries-javascript (/Users/andrew.eisenberg/codeql-home/tests)
codeql-java (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/java/ql/src)
codeql-java-tests (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/java/ql/test)
codeql-java-upgrades (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/java/upgrades)
codeql-javascript (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/javascript/ql/src)
codeql-javascript-tests (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/javascript/ql/test)
codeql-javascript-upgrades (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/javascript/upgrades)
codeql-python (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/python/ql/src)
codeql-python-tests (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/python/ql/test)
codeql-python-upgrades (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/python/upgrades)
codeql-suite-helpers (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/misc/suite-helpers)
legacy-libraries-cpp (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/misc/legacy-support/cpp)
legacy-libraries-csharp (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/misc/legacy-support/csharp)
legacy-libraries-java (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/misc/legacy-support/java)
legacy-libraries-javascript (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/misc/legacy-support/javascript)
legacy-libraries-python (/Users/andrew.eisenberg/git-repos/github/vscode-codeql-starter/ql/misc/legacy-support/python)
legacy-upgrades (/Users/andrew.eisenberg/codeql-home/codeql/legacy-upgrades)
```

Notice that only one of them is contained within the root folder. I think we want to filter all packs that are not contained in the current folder. But, I want to make sure of this before implementing.

**Comment by adityasharad** [comment]
I think your suggestion makes sense. It might be even simpler to pass only the root folder's pack directly to the test discovery, since we already know what it is when creating the `--additional-packs` argument, instead of retrieving them all and then filtering.

@dbartol I'd like to hear what you think, in particular whether there are situations where you _do_ want to see the tests for a pack's dependencies also listed under that pack in the test explorer.

**Comment by dbartol** [comment]
>One solution is to filter all packs that are not contained in the current folder. But, I want to make sure of this before implementing.

I _think_ this is the right solution. Note that you have to be careful when one workspace folder is an ancestor of another workspace folder.

>There might be a way to think of this as a feature, not a bug. It might be the case that tests run in the context of different workspace roots will behave differently, so maybe we want to allow this duplication.

Well, it's certainly not an _intentional_ feature:smirk: I would think that the only way for tests to be run in a different context depending on the workspace folder is if there are workspace-folder-specific library path settings in the `settings.json` file, and I'm not sure we even support that. Even if we do, I think that it only makes sense to run a test with the settings from its own workspace folder.

**Comment by dbartol** [comment]
>It might be even simpler to pass only the root folder's pack directly to the test discovery, since we already know what it is when creating the --additional-packs argument, instead of retrieving them all and then filtering.

If I use the `cpp` directory from the `github/codeql` repo as my workspace folder, there is neither a `qlpack.yml` nor a `.codeqlmanifest.json` in the root of the workspace folder, but I'd still expect to see any packs with tests underneath the `cpp` directory.

**Comment by adityasharad** [comment]
> > It might be even simpler to pass only the root folder's pack directly to the test discovery, since we already know what it is when creating the --additional-packs argument, instead of retrieving them all and then filtering.
> 
> If I use the `cpp` directory from the `github/codeql` repo as my workspace folder, there is neither a `qlpack.yml` nor a `.codeqlmanifest.json` in the root of the workspace folder, but I'd still expect to see any packs with tests underneath the `cpp` directory.

Excellent point, thank you: the workspace root is not always a QL pack itself, but may contain QL packs. Good to be reminded that we have to make this work for both multiroot workspaces and single open folders!

**Comment by aeisenberg** [comment]
Fix is simple. This should address everything you both said.
