### ISSUE TITLE
User should be able to configure page size in results viewer

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#525]
Currently, the page size in the results viewer is fixed at 100. The user should be able to configure this for other page sizes.

My thought is that on the results page, we include a drop down next to the pagination section where the user can pick different page sizes. Say: 50, 100, 200, 500, 1000, 2000. And perhaps this value should be a regular setting as well so it can be saved across restarts.

**Comment by aschackmull** [comment]
I would definitely like this to be a regular setting. 100 is too low for me, and I would find it annoying if I had to repeatedly select a higher number in a dropdown.  In fact, for me a dropdown would just add clutter, so I'd be fine with only having this as a regular setting and no dropdown.

**Comment by adityasharad** [comment]
Wrong issue link: I believe this is still open.
