### ISSUE TITLE
Run queries in folders on an old database opens many upgrade dialogs

### ISSUE THREAD

**Issue by johnlugton** [github/vscode-codeql#534]
**Describe the bug**
When using "Run queries in selected files" on a CodeQL db that needs an upgrade you get the dialog once per query.

**To Reproduce**
Try to run multiple queries at once on an outdated CodeQL db

**Expected behavior**
One upgrade prompt between all queries

**Comment by aeisenberg** [comment]
Thanks for reporting this bug. Our multi-run query operation is too simplistic. We're simply invoking the _run_ command once for each selection, which allows for this bug as well as #464.
