### ISSUE TITLE
Configure limits for running multiple queries

### ISSUE THREAD

**Issue by adityasharad** [github/vscode-codeql#547]
**Is your feature request related to a problem? Please describe.**
When running multiple queries (e.g. from a folder), the number of queries is currently capped at 20 to preserve resources and enable cancellation.

**Describe the solution you'd like**
Consider making the limit configurable, and warning the user when they attempt to run more queries than the limit.
Improve the mechanism for cancelling a batch of queries.

cc @sj @kllund

**Comment by aeisenberg** [comment]
Fixed by #588
