### ISSUE TITLE
Add ability to run queries over multiple databases at once

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#569]
Some enterprise customers have asked for this capability. Even though it's useful, perhaps they should be using code-scanning instead.

**Comment by shati-patel** [comment]
This will (eventually) become useful for query console work, so I'll start experimenting a bit!

Some options discussed earlier:
- Try adding a new command to "run query on multiple databases" and then use a multi-select list of databases to run on.
- Could also try adding a command from the Databases UI to "run query on selected databases" and then ask user to choose a query.
