### ISSUE TITLE
Problems handling non-printable chars

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#584]
Non-printable characters in a results cell are not escaped. Eg- `\b` is displayed as what appears to be an empty string.

Two possible solutions that I can think of right now:

1. add a quote to all strings that either start or end with a non-printable character
2. preprocess all result strings and convert a subset of non-printable chars to their unicode number (ie- `\uXXXX`). We probably only want to do this for a fixed set of chars, probably the ascii chars that are known to be control characters.

**Comment by mattt** [comment]
Another option might involve mapping non-printing characters to their counterparts in the [Control Pictures](https://en.wikipedia.org/wiki/Control_Pictures) unicode block. For example, in the case of `\b` (BACKSPACE U+0008) you could show ␈(SYMBOL FOR BACKSPACE U+2408). Those only covers the [C0 control codes](https://en.wikipedia.org/wiki/C0_and_C1_control_codes), but that may be sufficient depending on your use case.

**Comment by aeisenberg** [comment]
Thanks for your comment. This is a good possibility. Before deciding on an approach, I will contact some of our users who have hit this issue and determine what would make the most sense for them. This is a rare scenario so far and usually comes up when a user creates queries that are specifically looking for hidden control codes in code files, which could indicate something malicious.

**Comment by justinjao** [comment]
Hello @aeisenberg, I'd like to take a crack at working on this, if the issue is still open!

**Comment by marcnjaramillo** [comment]
I think either approach would work. I'm wondering, though, if we add quotes to strings that contain pre-determined sequences of non-printing characters will those sequences actually be visible or would the results just have some strings in quotes and some that aren't in quotes? I haven't had to do anything like this, so I'm not sure what the end result would look like. I like the idea of converting the characters to their unicode numbers, but would that be enough to draw attention to them?

**Comment by aeisenberg** [comment]
Many of the non-printable characters will still be invisible if we just surround them in quotes, though at least users would be able to see that something exists in the cell, even if it's opaque exactly what this value is.

So, I'd say it is better to do something slightly more sophisticated. Dealing with unicode can get extremely complicated extremely quickly. So, at least at first, it's best to keep it simple. We would want to display all non-printable characters as something, so displaying unicode values would be sufficient, something like `U+0008` for `\b` would be simple. 

If you wanted to try to display control pictures for unicode values that have them, this would be fine, too (but not strictly necessary).

**Comment by marcnjaramillo** [comment]
Sounds good. I think just displaying the unicode values will be a good start.

**Comment by mattt** [comment]
@marcelolynch You should be able to iterate through each code point in the string in linear time. Each C0 control character (U+0000 – U+001F) have a corresponding control picture with the at U+240x, which you can get by adding the offset `0x2400`. For any other characters, a `switch` statement would probably be your best bet.
