### ISSUE TITLE
Sorting in the result viewer is not preserved when reloading the results.

### ISSUE THREAD

**Issue by aschackmull** [github/vscode-codeql#587]
**Describe the bug**
If I sort a set of results by clicking a column, and then reload the results by clicking in the Query History (either directly or after having viewed some other result set), then the column that I sorted on is remembered and displayed, but the results are no longer sorted as indicated by the triangle next to the column name.

**To Reproduce**
Execute a query. For example the following:
```ql
from int x, int y
where x in [1..2] and y in [1..2]
select x, y
```
Click a column to sort the results (the sorting must differ from the default ordering in order for the problem to be observable), in this case clicking `y` should do the trick. Click the line for the query in the Query History, such that the results reload. Observe that `y` is still highlighted as the sorted column, but the tuples are back in the default order.

**Expected behavior**
I expect either that the triangle would be cleared when reloading results to indicate that the sorting was forgotten, or alternatively, since the sorted column is clearly remembered and redisplayed with the triangle icon, that the sorting is reapplied. The latter option seems to be the more useful option.

**Comment by aeisenberg** [comment]
The issue here is that when we reload the query results, the previous sort infos are not flushed and we are not using this previous sort info to actually display the results.

Either, we need to flush the sort infos, or we need to use them to display the results when we re-load.
