### ISSUE TITLE
Format document deletes query metadata

### ISSUE THREAD

**Issue by rvermeulen** [github/vscode-codeql#589]
**Describe the bug**
The format document command deletes query metadata if it is the only contents of the file.

**To Reproduce**
1. Create a query file containing only metadata.
2. Format the document via the `Format document` command.

**Expected behavior**
Format (not as in format disk) the metadata or leave it as is.

**Additional context**
This is easily triggered with the option to format a document on save.

**Comment by aeisenberg** [comment]
This is a bug in the language server. I'll raise an issue there.

**Comment by rvermeulen** [comment]
Closed in favour of github/codeql-coreql-team#549
