### ISSUE TITLE
QL Test Explorer should discover tests via `codeql resolve tests`

### ISSUE THREAD

**Issue by dbartol** [github/vscode-codeql#595]
**Is your feature request related to a problem? Please describe.**
The current implementation of Test Explorer finds QL tests by looking for packs from the current workspace that are available on the CLI's library path (usually via `.codeqlmanifest.json`), then looking for tests within those packs. This misses tests in packs that aren't specified in `.codeqlmanifest.json`, even though packs containing only queries and tests, or even packs containing only tests, have no other reason to be specified in the manifest.

**Describe the solution you'd like**
Instead of searching for registered packs, the Test Explorer should just invoke `codeql resolve tests` from the root of the workspace.

**Additional context**
A related concern exists about how the Test Explorer tree displays the tests. It currently has one top-level node for each pack, which will then expand to a directory tree containing the individual tests and test directories. It has been suggested that it would be better to have the Test Explorer tree show the actual directory tree, similar to the file Explorer tree. Directories containing no tests would not be shown, and any directory containing only a single other test directory would be combined with the contained test directory:

Original file system:
```
root
+ A
  + A1
    - test_a1.ql
  + A2
    - test_a2.ql
+ B // No tests under here
  + B1
    + foo.txt
+ C  // Only one subdirectory contains tests
  + C1  // Only one subdirectory contains tests
    + D
      - test_d1.ql
      - test_d2.ql
```

Test Explorer tree:
```
root
+ A
  + A1
    - test_a1
  + A2
    - test_a2
+ C/C1/D
  - test_d1.ql
  - test_d2.ql
```

If the above would be a better way to display the tests, it might be worth switching to that when implementing the `codeql resolve tests` code, rather than having to figure out how to map the output of `codeql resolve tests` back to packs.

**Comment by aeisenberg** [comment]
Finally getting around to looking at this. Currently, we _are_ using `codeql resolve tests`. Implemented by you in January this year:  de2a6cc0b7c63b525945bb504ebf67034ac22717. Though it looks like we are running `codeql resolve tests` once per qlpack, instead of once per folder.

**Comment by aeisenberg** [comment]
Implementing this suggestion will simplify our discovery code. Though, I'm not sure if the UI is actually improved. The test discovery is much more deeply nested under this approach. See here:

<img width="346" alt="resolve in roots" src="https://user-images.githubusercontent.com/363559/96503413-094cd280-1208-11eb-8ed6-bd218c047510.png">

And this is what it looks like now:

<img width="348" alt="resolve in qlpacks" src="https://user-images.githubusercontent.com/363559/96503422-123da400-1208-11eb-8693-b4b02208fe02.png">

I'm agnostic as to which approach I prefer, so I could go either way depending on if there is consensus in changing the layout.

**Comment by dbartol** [comment]
I'd expect that we'd collapse folders with a single child into a single node, similar to what the file explorer view does:

```
ql - CodeQL
+ ql
  + cpp/ql/test
  + csharp/ql/test
  + java/ql/test
```

**Comment by aeisenberg** [comment]
We can do that:

<img width="366" alt="_Extension_Development_Host__-_expr_ql_—_vscode-codeql-starter__Workspace_" src="https://user-images.githubusercontent.com/363559/96512977-2be5e800-1216-11eb-96fa-b14b87892982.png">

Note that I also combined the top level and its first child (ie- `ql` has been merged into `ql - CodeQL`). Since there will always be exactly one child here that shares its name with its parent.
