### ISSUE TITLE
Setting for the number of threads does not accept 0

### ISSUE THREAD

**Issue by adityasharad** [github/vscode-codeql#603]
**Describe the bug**
@yoff reports that the settings UI for the number of threads when running queries or tests does not accept 0 as input.

**Expected behavior**
0 is passed to the corresponding CLI commands, where it is interpreted as 'use one thread per core on the machine'.
A positive integer continues to be used as-is, and a blank setting defaults to 1.

**Additional context**
CLI docs for `--threads` argument in [`execute query-server`](https://help.semmle.com/codeql/codeql-cli/commands/execute-query-server.html#cmdoption-codeql-execute-query-server-j) and [`test run`](https://help.semmle.com/codeql/codeql-cli/commands/test-run.html#cmdoption-codeql-test-run-j).

**Comment by yoff** [comment]
Thanks 🎉
