### ISSUE TITLE
Importing a .zip database kills the extension

### ISSUE THREAD

**Issue by agustingianni** [github/vscode-codeql#621]
**Describe the bug**
Importing a .zip database kills the extension

**To Reproduce**
- Download the C/C++ database from https://lgtm.com/projects/g/torvalds/linux/ci/#ql
- Import it from vscode.

**Expected behavior**
The database is imported

**Comment by aeisenberg** [comment]
Discovered a different, but related bug when looking into this.

Linux C++ is a very large database. The extension must be running into memory limits when trying to import.

**Comment by aeisenberg** [comment]
I just tried downloading the db and importing it as a zip. It worked for me. So, my guess would be this is a systems resource issue on your end. Can you let me know what sort of machine this is? Memory, architecture, OS, CPU, etc.

**Comment by agustingianni** [comment]
Downloading it as a zip and importing it does not work either.

My machine is a macbook pro, 2,5 GHz Quad-Core Intel Core i7, 16 GB 1600 MHz DDR3.

**Comment by aeisenberg** [comment]
I do wonder if 16 Gb is enough.

If you unzip the database yourself and import the database from the file system, does that work?

**Comment by agustingianni** [comment]
Yes it does work if I unzip it first and then load it. Weird.

**Comment by aeisenberg** [comment]
I think the difference is that importing as a zip through vscode, we are streaming the data through the extension and using more memory than unzipping directly from the OS. 

I may need to re-work how we approach this and unzip out of process.

**Comment by agustingianni** [comment]
Sweet, makes sense, let me know if I can help in any way.

**Comment by Manouchehri** [comment]
Hmm, I wonder if #699 is related? In my case, the extension doesn't die.
