### ISSUE TITLE
Encode URI is being passed as a source location into the archive-filesystem-provider

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#652]
**Describe the bug**

We are sometimes passing encoded uris into the archive-filesystem-provider for the path inside of the archive file. The file paths are all unencoded. And so, when we have a source location URI with special characters in it, the locations cannot be found inside of the archive.

**To Reproduce**

1. Create a database whose source is inside of a directory path with a special character in it (eg- create a space in one of the directory names)
2. Import database into the extension
3. Run a non-interpreted query that includes a source location
4. BUG: When clicking on the source location you are _not_ navigated to the source.

**Expected behavior**
You _are_ navigated to the source

**Additional context**
Interpreted queries (ie- problems and path problems) do not have this issue. The sarif values already have unencoded paths.

**Comment by aeisenberg** [comment]
We need to unencode only those locations that are from non-interpreted results. This _should_ happen in the extension side, not the webview side.

**Comment by RasmusWL** [comment]
I just experienced this from running a `path-problem` in VS Code.

I used the Python database from https://lgtm.com/projects/g/SuryaPradeepM/web-design with the new [CodeInjection query](https://github.com/github/codeql/blob/92494441a72cd1c04c9359dc8c0d35e2a4525f6d/python/ql/src/Security/CWE-094/CodeInjection.ql). The result location has spaces in it, and from the logs I see:

```
Unable to handleMsgFromView: cannot open codeql-zip-archive://.../SuryaPradeepM_web-design_d1625d1/src.zip/opt/src/web%2520design%2520assignment/form%2520project/intform.py. Detail: Unable to read file 'codeql-zip-archive://.../SuryaPradeepM_web-design_d1625d1/src.zip/opt/src/web%20design%20assignment/form%20project/intform.py' (EntryNotFound (FileSystemError): uri 'codeql-zip-archive://.../SuryaPradeepM_web-design_d1625d1/src.zip/opt/src/web%2520design%2520assignment/form%2520project/intform.py', interpreted as '/opt/src/web%20design%20assignment/form%20project/intform.py' in archive '.../SuryaPradeepM_web-design_d1625d1/src.zip')
```

**Comment by aeisenberg** [comment]
@RasmusWL, if you're feeling courageous, you can install the version of the extension built in this PR (see the checks page) and install that. I've verified that it is working on windows, but further verification would be nice.

**Comment by aeisenberg** [comment]
It's this PR #653. Forgot to include the link.

**Comment by RasmusWL** [comment]
nice, was just about to ask :smile:

**Comment by RasmusWL** [comment]
@aeisenberg can confirm that your fix allowed me to view the locations :+1:
