### ISSUE TITLE
CodeQL: Show Test Output Differences fails from the Command Palette

### ISSUE THREAD

**Issue by lcartey** [github/vscode-codeql#658]
**Describe the bug**
Choosing the `CodeQL: Show Test Output Differences` option from the Command Palette gives the following error:
```
Cannot read property 'info' of undefined
```
The command works fine when selected from the right-click context menu for the test in the Test Explorer

**To Reproduce**

 1. Run a CodeQL query test that fails
 2. Select the `CodeQL: Show Test Output Differences` option from the Command Palette.

**Expected behavior**
Ideally, it would show me the test output differences for the last test. Otherwise, can we hide it from the Command Palette? Or at least not throw an error?

**Comment by aeisenberg** [comment]
Thanks for raising this issue.

**Comment by aeisenberg** [comment]
Yes, this command and the `codeQLTests.acceptOutput` command need to be disabled on the palette since they are not applicable in the global context. I'll have to remove them.
