### ISSUE TITLE
AST viewer uses `node.toString` for labels and ignores `value`

### ISSUE THREAD

**Issue by nickrolfe** [github/vscode-codeql#659]
Here's a simple, language-agnostic print-AST query implementation:

```codeql
/**
 * @id foo/print-ast
 * @kind graph
 * @tags ide-contextual-queries/print-ast
 */
class Node extends string {
  Node() { this in ["foo", "bar", "baz"] }

  Node getChild() { this = "foo" and result in ["bar", "baz"] }
}

query predicate nodes(Node node, string key, string value) {
  key = "semmle.label" and
  value = node.toUpperCase()
}

query predicate edges(Node source, Node target, string key, string value) {
  source.getChild() = target and
  key = "semmle.label" and
  value = "edge"
}

query predicate graphProperties(string key, string value) {
  key = "semmle.graphKind" and value = "tree"
}
```

And here's how it looks in the AST viewer:
![image](https://user-images.githubusercontent.com/158306/98007295-1c0bfd80-1deb-11eb-9793-234f1726af36.png)

My understanding after a discussion with @dbartol is that the AST viewer is expected to use the `value` argument as the label for nodes, but instead it uses `node.toString()`. You can see in the screenshot that the labels are lower-case, so `value` is not being used.

**Comment by aeisenberg** [comment]
That's probably a bug. Thanks for raising this issue.
