### ISSUE TITLE
Periodically and on demand clean up old databases in the extension

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#674]
Most of the time when a user removes a database, it is also cleared from disk, but sometimes this doesn't happen. I haven't figured out the precise situations where this can occur, but I think it has something to do with workspaces that aren't shut down properly (ie- vs code crashes). And it may be more likely on windows which more aggressively locks folders.

The proposal here is to create a command that will look in workspace storage for any abandoned databases. This command can be run on demand, and also in the background after startup. (Arguably, we may not want to expose this command directly to users since it really is a plumbing command.)

It will work like this:

1. get all directories in workspace storage
2. check each directory to see if it is a database
3. check if this database is currently imported in the workspace
4. if not delete the entire directory

**Comment by nickrolfe** [comment]
I suspect the reason the databases don't get removed on Windows is because of #249. The open query-server lock will keep a file handle open that will cause deletion to fail.

**Comment by aeisenberg** [comment]
I have a simple fix. Let's see if that helps you. It will help me since I had about 30 old dbs laying around from when vscode crashed while debugging.
