### ISSUE TITLE
Error when deleting database that doesn't exist on disk anymore

### ISSUE THREAD

**Issue by max-schaefer** [github/vscode-codeql#693]
**Describe the bug**
When trying to delete a database from the UI that doesn't exist on disk anymore, I sometimes get "Cannot read property 'belongsToSourceArchiveExplorerUri' of undefined", possibly originating [here](https://github.com/github/vscode-codeql/blob/1b4d8e303d92a1e89189fe565e9cbbf0742ea58f/extensions/ql-vscode/src/databases.ts#L686) (though this is a guess, since I don't have a stack trace).

**To Reproduce**
- Create a new database, for example using `codeql test run`
- Import it
- Exit VSCode
- Remove the database
- Start VSCode again; the database now displays a red cross next to it.
- Try removing the database; the log will show a message about "Removing workspace folder at index -1", possibly caused by the typo fixed in #692. The database is not removed.
- Try removing the database again; the log will show the message mentioned above.

**Expected behavior**
It should delete the database.

**Comment by aeisenberg** [comment]
This issue is fixed by #692.
