### ISSUE TITLE
"Show in AST viewer" command

### ISSUE THREAD

**Issue by p0** [github/vscode-codeql#707]
**Is your feature request related to a problem? Please describe.**
I'd like an easy way to view the AST of a particular construct. One workflow I keep trying is right-clicking in a source archive file, and looking for a "show in AST viewer" option.

**Describe the solution you'd like**
A new command for showing the current file in the AST viewer (if it isn't already there) and navigating to the node whose location is at the cursor.

**Describe alternatives you've considered**
The current workaround is to navigate to the AST viewer pane, clear the current AST, show the AST for the current file, and then click once more on the construct I want the tree view to navigate to. This could be condensed into a single command invocation.

**Comment by aeisenberg** [comment]
Hmmm...it _should_ be the case that you can invoke "CodeQL: View AST" from the command palette (if the active editor is in a source archive) or from the file explorer by right clicking on a file in a source archive. Is this not working for you?

It would be a nice feature to automatically select the AST node corresponding to the current position of the caret.

The first part is potentially a bug and the second part is a feature enhancement.

**Comment by p0** [comment]
Huh, somehow I didn't realise I could use the command palette to trigger AST view on the current file, and that it would replace any currently displayed AST -- my workflow was around clicking the 'show AST' button in the viewer pane, preceded, if necessary, by a click on 'clear AST' in order to make the button visible again. I definitely do not have that option in my right-click context menu, and if it had been there I probably would have discovered it.

Running the command manually (and then clicking to focus on an element's location) is actually enough to unblock me here.

**Comment by aeisenberg** [comment]
Hmmm...I just want to make sure that you're not seeing something like this:

<img width="774" alt="_Extension_Development_Host__-_affix_js__read-only__—_vscode-codeql-starter__Workspace_" src="https://user-images.githubusercontent.com/363559/102404112-17b33280-3f9c-11eb-9560-42b11d0d2d6c.png">

**Comment by p0** [comment]
I right-click in the actual source-code view, and I don't see it there.

**Comment by aeisenberg** [comment]
Ah...yes. That's not implemented. It might be something easy to do. And if so, I'll slip it in right before the next release.
