### ISSUE TITLE
vscode extension for go does not show the link of results

### ISSUE THREAD

**Issue by madneal** [github/vscode-codeql#715]
**Is your feature request related to a problem? Please describe.**

For the golang codeql query, the result does not have the corresponding link to the specific line of code.

![image](https://user-images.githubusercontent.com/12164075/102712789-8e369400-42fe-11eb-842d-4968673d573b.png)

But for the javascript codeql query or other languages, there are.

![image](https://user-images.githubusercontent.com/12164075/102712829-ca69f480-42fe-11eb-8ad0-bf3464132cc5.png)

**Describe the solution you'd like**

There should be the corresponding link to the specifc line of code.

**Comment by aeisenberg** [comment]
Thanks for raising the issue. The behaviour you are seeing is expected. In the go libraries, instances of `Method` and `Variable` are not `Locatable`, which means they do not directly have location information attached to them. If you want location info, then you need to reference the declaration. 

The following query will do what you want:

```ql
import go

from Method m, Variable v
where v = m.getReceiver()
select m.getDeclaration(), v.getDeclaration()
```

**Comment by madneal** [comment]
@aeisenberg  Thanks a lot !
