### ISSUE TITLE
What is the best way to cache compiled queries for further transfer on another machine to skip first stage of "database analyze"

### ISSUE THREAD

**Issue by japroc** [github/vscode-codeql#730]
I want to cache compiled queries. That cached queries i want to transfer between machines. The idea is to skip first stage  (query compilation) on executing `codeql database analyze` for accelerating projects analysis.

I've detected some cache files in `db-<lang>/default/cache` and `codeql/<lang>/ql/src/.cache/` folders. Also there are some options like `save-cache`, `keep-full-cache`, and entities like `DIL`, `.qlo` files and QL dataset.

What is the best way to cache compiled queries fur further transfer and reuse? How to handle newer revisions of codeql queries repository? How to handle custom queries?

**Comment by alexet** [comment]
The queries can be compiled via `codeql query compile` which will compile and optimise the the queries and store the result in the cache. It is general best to run that on the queries/suites you want to compile and then copy the entire folder containing queries (including the `.cache` folder). The cache will work across all platforms but not across codeql versions or chnages to the queries. Custom queries can be handled the same.

Most of those cache options relate to the database evaluation cache which cannot be shared across databases as it depends on the database.
