### ISSUE TITLE
"No result from server" after changing codeql path

### ISSUE THREAD

**Issue by alexet** [github/vscode-codeql#733]
If after running a query I change the path to codeql and then run another query I get `No result from server` printed into the extension log and as a message. The queryserver log shows  `- - - COMPILATION DONE - - - ` which shows that compilation seems to have happened.

Restarting vscode seems to fix this but restarting the query server doesn't seem to fix it.

**Comment by aeisenberg** [comment]
Are you using a regular released version of codeql or a custom built the codeql cli? If custom, what sha did you build from? I am not able to reproduce.

**Comment by aeisenberg** [comment]
Though, you're on linux, so I'll try on that platform.

**Comment by aeisenberg** [comment]
OK...tried it out on linux and I see the error. It must be platform specific.

**Comment by aeisenberg** [comment]
No...I can reproduce on mac. The problem exists on cli v2.4.2 and v2.4.1, but not v2.4.0. This looks like an issue introduced in the cli.

**Comment by adityasharad** [comment]
Diagnosis: when the extension restarts the query server, it needs to re-register the databases from the workspace, and currently does not. This applies only to CLI 2.4.1+ because that is when we introduced database registration.
