### ISSUE TITLE
Support downloading databases from LGTM.com using just the project slug

### ISSUE THREAD

**Issue by tausbn** [github/vscode-codeql#755]
**Is your feature request related to a problem? Please describe.**
When specifying a database on LGTM.com to download, one has to specify the entire URL for the corresponding project, even though the project slug should be sufficient. In much of our tooling, projects are identified using just the slug, and so it's more difficult to quickly import a database of interest than it perhaps ought to be.

**Describe the solution you'd like**
Ideally, the extension would recognise strings that match LGTM.com slugs (e.g. `g/github/codeql` or `b/bitbucket/whatever`) and automatically add the `https://lgtm.com/projects/` prefix.

**Describe alternatives you've considered**
My current alternative is to manually type in the prefix. This gets old fast.

**Additional context**
None.

**Comment by aeisenberg** [comment]
Yep. This makes sense. The original implementation assumed users would copy/paste from the browser's url bar. It shouldn't be hard to implement a different way of specifying the database name.
