### ISSUE TITLE
Improve discoverability of errors that break the alerts view

### ISSUE THREAD

**Issue by p0** [github/vscode-codeql#759]
**Describe the bug**
In [a recent discussion](https://github.com/github/securitylab/discussions/274#discussioncomment-388467), @adriaanjacobs asked about a situation where the alerts view was silently unusable for a particular path query against a particular database. Ultimately, there was an error in the extension output pane, which indicated that we had [encountered an exception](https://github.com/github/vscode-codeql/blob/ab31d86a8d7e09926772e0b84744e8a45639be47/extensions/ql-vscode/src/interface.ts#L630) while processing interpreted results, and were falling back on raw display.

While that's certainly better than not displaying results at all, it would be nice to find a way of making it clear why the `alerts` view is non-functional (perhaps by replacing it with an error pane that shows details about the exception we caught?).

**To Reproduce**
I have a database and query that reproduce the problem -- ping me on Slack if it would be useful to have them.

**Comment by aeisenberg** [comment]
The underlying error here is that the resulting SARIF file is too large for us to process. `Error: Cannot create a string longer than 0x1fffffe8 characters`. This is a node error that we get when we try to create a string that is too long. I could surface that error more prominently in a non-modal popup, but it's still not very meaningful for most users.

I think the most reasonable thing to do would be to show it like we show other errors and add some more context as to why we are getting this error.

(A more robust solution would be to properly handle large strings like this by using a streaming json parser, which is something I would like to do in the future.)

**Comment by aeisenberg** [comment]
Will look like this:

<img width="469" alt="_Extension_Development_Host__-_addresstocondjump_ql_—_vscode-codeql-starter__Workspace_" src="https://user-images.githubusercontent.com/363559/109705198-5b095000-7b4c-11eb-92c0-382793b226c9.png">
