### ISSUE TITLE
Support Sorting in Query History View

### ISSUE THREAD

**Issue by Ovi3** [github/vscode-codeql#767]
**Problem description**
After run a lot of query, there're a lot of item in Query History View. And  I wanna choose those item that has at least one result. 
Is there a way to filter those items? If not, this issue is a feature request.

**Describe the solution I'd like**
Filter function in Query History View

**Comment by aeisenberg** [comment]
There's no exact way to do this at the moment, but there are two features you can use that might help.

1. You can remove any history item (select and click the trash can icon).
2. You can rename any history item (right click and select "set label").

Rather than filtering, I think a more useful option would be to support sorting by name, date added, and by result count.

**Comment by Ovi3** [comment]
Yeah, sorting is a better way. Thanks for the help.

**Comment by aeisenberg** [comment]
This is a reasonable feature request. I don't know when we will get to it, but I'd like to keep it open so that we can in the future.

**Comment by aeisenberg** [comment]
@edoardopirovano 👋🏼 Welcome!

First take a look at the way we are sorting databases. We have two options (date and name) there and you can use the same icons, etc. And as to answering your questions:

1. I think that's entirely reasonable. Go for it. 
2. This is trickier as you mention. The easiest thing to do would most likely be to fill in the result count when you first open the query results page (all queries are opened immediately after being completed). You might be able to do this here: https://github.com/aeisenberg/vscode-codeql/blob/be9084e83e39d87a82d1760085ee34de88571390/extensions/ql-vscode/src/extension.ts#L448-L453 Though, that will need some more exploration.

So, maybe it's best to focus on 1) first and get to 2) later.
