### ISSUE TITLE
Test failures are not properly reported

### ISSUE THREAD

**Issue by Marcono1234** [github/vscode-codeql#774]
**Version**
Extension Version: 1.4.3
CodeQL CLI Version: 2.4.4

**Describe the bug**
It appears the VSCode extension invokes CodeQL CLI with `--format jsonz`. With that format only a small portion of the information is written to stdout, most of the information is inside the JSON data. With #626 some of the JSON data is read, but apparently not all. Most notably, the extension is apparently not reading `failureDescription`.

This makes understanding test failures pretty difficult, for example when no `.expected` file exists (see also https://github.com/github/codeql/issues/5343).

**To Reproduce**
1. Clone https://github.com/github/codeql
2. Delete [`cpp/ql/test/library-tests/dataflow/DefaultTaintTracking/annotate_sinks_only/remote-flow-sink.expected`](https://github.com/github/codeql/blob/main/cpp/ql/test/library-tests/dataflow/DefaultTaintTracking/annotate_sinks_only/remote-flow-sink.expected)
3. Run only the corresponding test file `remote-flow-sink.ql` from the "Test" tab of VSCode
:x: The output only says (roughly)
    > 0 tests passed; 1 tests failed:
    > FAILED: path/to/test.ql
    > failed: path/to/test.ql
    > Query produced no results.

**Expected behavior**
The VSCode extension should evaluate the `failureDescription`, if present, (and maybe more members of the JSON data) of the test result and inform the user.

**Comment by aeisenberg** [comment]
Thanks for raising this issue. I see how this could have clarified things on https://github.com/github/codeql/issues/5343.

**Comment by Marcono1234** [comment]
I was mostly writing this from the perspective of `InlineExpectationsTest` which has empty `.actual` and `.expected` files, but it appears for tests with a non-empty `.actual` file, even when the `.expected` file is missing (and a `failureDescription` is present), it still generates useful `diff` results. So maybe the `failureDescription` should be evaluated in addition to `diff`?

**Comment by Marcono1234** [comment]
Has been fixed by #788; in version 1.4.4 of the extension the missing `.expected` file is now correctly reported.
