### ISSUE TITLE
Support copying version information

### ISSUE THREAD

**Issue by Marcono1234** [github/vscode-codeql#795]
**Is your feature request related to a problem? Please describe.**
It would be useful if:
- The extension provided a way to copy version information, i.e. extension version (maybe also VSCode version + operating system?) and CodeQL CLI version
- The GitHub issue template for bug reports required version information

This would probably make reproducing issues earier, and in case a GitHub issue cannot be handled immediately, it is still later on comprehensible in which version the issue occurred.

**Describe the solution you'd like**
1. The extension should allow copying version information, e.g. by running a command or from a context menu opened clicking the text "CodeQL CLI vX.Y.Z" in the bottom right corner
2. The GitHub issue template for bugs should have a section called "**Version**" (or similar) which tells the user to perform the extension action to copy version information

**Describe alternatives you've considered**
An alternative, or additional feature might also be generate and open a GitHub issue link from within the extension. This link could then contain the relevant information as [URL query parameters](https://docs.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters).

**Comment by adityasharad** [comment]
Thanks, these are both good ideas. We're unlikely to pick this up soon, but I'll leave this open so we can include it future.
