### ISSUE TITLE
"View AST" for files outside of database

### ISSUE THREAD

**Issue by Marcono1234** [github/vscode-codeql#796]
**Is your feature request related to a problem? Please describe.**
Currently the "View AST" command only works for files inside of databases. It would be useful if it would work for all files (which Java's `autobuild` is able to build).

Possibly slightly related to #306

**Describe the solution you'd like**
"View AST" should work for source files outside of databases.
(If necessary creating a database in a temporary directory.)

Open questions:
- When should the temporary database be deleted?
- Should source and AST be linked (e.g. clicking on AST node scrolls to corresponding source code element)?
  - What should happen when the source file is modified?
  - Should the read-only source file from the database be opened, and only for that the AST is linked?

**Describe alternatives you've considered**
Current workaround:
1. Manually create the database
2. Import the database
3. Locate the source file in question
4. Use "View AST"

**Comment by adityasharad** [comment]
Thanks for the suggestion. https://github.com/github/vscode-codeql/issues/306 will indeed have to happen first. We don't have plans to work on this any time soon, so I'll close this for now and reopen if priorities change.
