### ISSUE TITLE
Test compilation errors appear in output diff

### ISSUE THREAD

**Issue by Marcono1234** [github/vscode-codeql#819]
**Version**
CodeQL CLI v2.5.0
Extension version: v1.4.5

**Describe the bug**
When compilation of a test fails, the extension currently creates an output diff between the expected output and the compilation error, which is pretty pointless and confusing. E.g.:
```
--- expected
+++ actual
@@ -1,12 +1,1 @@
-| Expressions.java:5:9:5:18 | toString(...) |
-| Expressions.java:9:9:9:13 | ...=... |
-| Expressions.java:10:9:10:11 | ...++ |
-| Expressions.java:11:9:11:20 | new Object(...) |
-| Expressions.java:14:9:14:28 | clone(...) |
+ERROR: no viable parse for input 'a', expecting one of : 'boolean', 'class', 'newtype', 'date', 'float', 'from', 'import', 'int', 'module', 'predicate', 'select', 'string', 'where', Lowerid, Upperid, Atlowerid (Expressions.ql:6,1-2)
```

It looks like the underlying issue might be caused by the CodeQL CLI which reports this as `diff`. It appears this is currently 'misused' to perform tests on CodeQL itself, see https://github.com/github/vscode-codeql/issues/608#issuecomment-702933731.
Regardless of whether that is intended or not, the extension could inspect the `failureStage` of the response, only if it is `"failureStage" : "RESULT"` the diff should be shown.

**To Reproduce**
1. Create an `.expected` file
2. Create a query test file containing a compilation error
3. Run `codeql test run --format=json`

**Expected behavior**
Only the compilation error is reported, the diff is not shown.

**Comment by aeisenberg** [comment]
Thanks for reporting. We've added this to our backlog.

**Comment by aeisenberg** [comment]
Thanks for adding a bounty to this @tylermaran. We are happy to accept and facilitate external contributions.

**Comment by aeisenberg** [comment]
The solution we are considering here would be a better presentation of these kinds of compiler error messages. This would lead to a change in how we parse the output of `codeql test` in the extension. It would not require any changes to the cli itself.

**Comment by eyskim** [comment]
Hi @aeisenberg, I would like to work on this issue if nobody has picked it up yet.

**Comment by aeisenberg** [comment]
Hi @eyskim, I assigned this issue to you. No one else is currently working on it. Thanks for volunteering!

See here for information on how to run codeql tests in vscode: https://codeql.github.com/docs/codeql-for-visual-studio-code/testing-codeql-queries-in-visual-studio-code/

And the change will likely have to be in this function: https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/src/test-adapter.ts#L277-L305
