### ISSUE TITLE
User-specified directory in which to store evaluation logs

### ISSUE THREAD

**Issue by tausbn** [github/vscode-codeql#820]
**Is your feature request related to a problem? Please describe.**
In the course of my work, I end up creating a lot of evaluation logs that I subsequently scrutinise in order to do things like fix bugs and improve performance. I also occasionally have to restart VSCode (by choice or by necessity), and the fact that logs do not persist across restarts of VSCode is problematic in this regard.

**Describe the solution you'd like**
I would like the possibility of specifying a place where VSCode should place the evaluation logs. VSCode should _never_ attempt to remove old logs from this directory automatically. The onus will be on the user to do this cleanup themselves (though one _could_ add a way to do this in the VSCode extension as well, for instance as a button associated with the "query history" view).

**Describe alternatives you've considered**
My current alternatives include
- Eagerly backing up all logs before restarting VSCode (but I sometimes forget, leading to much loss of work and subsequent cursing)
- Running the `codeql` CLI command manually, to ensure that I can control where the log ends up (but this adds friction, as it takes me out of the nice VSCode extension).

Also, eagerly backing up logs isn't always possible: on a Codespaces instance, I have no way (that I know of) of accessing the instance _before_ it starts up VSCode, and so my logs will always get purged before I can get to them and safely back them up.

**Additional context**
N/A

**Comment by adityasharad** [comment]
Proposed breakdown:
- add a new user setting to specify where to store query logs (if blank, we use the default of the workspace storage folder)
- if the setting is provided, use it in the output channel loggers as their additional logging location
- if the setting is provided, don't automatically clean up old logs when each logger object is constructed
