### ISSUE TITLE
Options to view results as CSV or SARIF not displaying

### ISSUE THREAD

**Issue by edoardopirovano** [github/vscode-codeql#821]
Had a bug report from @Manouchehri stating that he could not see the "View Results (CSV)" or "View Results (SARIF)" options when right clicking in the Query History view. Screenshot attached. He is running version 1.4.5 of the extension.

![image](https://user-images.githubusercontent.com/6748066/114212958-52314880-995a-11eb-8e7c-2d1ddb4bcbe1.png)

**Comment by Manouchehri** [comment]
To provide more context, I'm also using VS Code Remote (containers).

**Comment by Manouchehri** [comment]
The option is showing up on my Mac, so it's just my Linux machine that's having this issue.

**Comment by aeisenberg** [comment]
Not able to reproduce this in VS Code remote. Are you still having this problem?

**Comment by edoardopirovano** [comment]
I also was not able to reproduce this.

**Comment by edoardopirovano** [comment]
Closing this as it does not seem to be occurring any more, feel free to reopen if you are still experiencing this issue!
