### ISSUE TITLE
Unable to view source code inside of a database

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#828]
**Describe the bug**

A user has provided me with a database where attempting to view source code displays an error. The database is private so I cannot share it.

**To Reproduce**

Import the database and click on any source file from `src.zip`. The following is printed in the logs `(Error: invalid stored block lengths)`

**Expected behavior**

Should be able to view the source file.

**Additional context**

Work around is to unzip the src.zip, delete the file, and let the extension use the legacy version of being able to read unzipped source folders.

**Comment by aeisenberg** [comment]
@Manouchehri I tried the database you sent me and was not able to reproduce the issue. Are you running on linux? It's possible there is a difference in the zip libraries between macos and linux, but that does seem a bit surprising.

**Comment by Manouchehri** [comment]
I'm running on Linux, with VS Code Remote (Docker container). The client, Docker host, and container are all Linux.

**Comment by aeisenberg** [comment]
Oh. vscode remote. I think it might be this issue #242. I haven't had an opportunity yet to look at it, but I have some spare cycles over the next few days and I will try.

**Comment by Manouchehri** [comment]
Hmm, technically I think the path is "local", no? The database folder is in the remote container (where VS Code Remote's server is running). 

Also, I have seven other databases working perfectly in the same workspace. 🙂 It's just this 8th one that's an issue for some reason.

**Comment by aeisenberg** [comment]
Yep. Might be unrelated. Just tried using this database in a vscode remote container and source code lookup works fine for me. 🤷🏼 

Are you able to use this database in a normal (non-remote) workspace? Also, you get this problem every time you recreate this database?

**Comment by Manouchehri** [comment]
Odd.. No issues when connecting from my MBA from home today.

Was getting it repeatedly at work from my Linux machine. Will try again tomorrow to see if it's still happening.

**Comment by aeisenberg** [comment]
Is this still an issue for you?

**Comment by aeisenberg** [comment]
Doing some tidying of old issues here. I don't think we were able to reproduce this issue. I'll close it, but if you have more information or are still having this problem, we can look again.
