### ISSUE TITLE
Option to clear database cache

### ISSUE THREAD

**Issue by edoardopirovano** [github/vscode-codeql#885]
**Is your feature request related to a problem? Please describe.**
When debugging query performance, it would be helpful to be able to easily run queries from a clean database cache.

**Describe the solution you'd like**
An option when right clicking on a database called something like "Clear cache" that runs `codeql database cleanup --mode brutal` would address this.

**Describe alternatives you've considered**
Manually running the above command from a Terminal works, but its a pity to not be able to do it directly in VS code.

**Comment by adityasharad** [comment]
Does the `CodeQL: Clear Cache` command do what you need? (It runs through the query server rather than a separate `cleanup` call, but I expect it to be enough for clearing the evaluation cache between runs.)

**Comment by alexet** [comment]
In fact `codeql database cleanup --mode brutal` will break the queryserver where `CodeQL: Clear Cache` won't.

**Comment by edoardopirovano** [comment]
Ah, yes, that is exactly what I need. Thanks both 🙂
