### ISSUE TITLE
[Feature Request] Customize number of paths per alert

### ISSUE THREAD

**Issue by gsingh93** [github/vscode-codeql#919]
The path view seems to show a maximum of four paths per alert, with no option to customize it. Eclipse had an option to customize this: https://help.semmle.com/ql-for-eclipse/Content/WebHelp/preferences.html. I don't see any similar option in the settings for this extension, could an option be added to customize this?

---

### Implementation notes
- Add a `maxPaths` setting, probably under `runningQueries`
- Pass that value through to `codeql bqrs interpret` and `codeql database interpret-results` using their `--max-paths` argument.

**Comment by adityasharad** [comment]
Thanks for the suggestion! You're right that this option was available in CodeQL for Eclipse and hasn't yet made its way into VS Code. I agree it's something we should provide, and we'll pick this up in the next few weeks.
