### ISSUE TITLE
Allow viewing results from any query runs as CSV

### ISSUE THREAD

**Issue by RasmusWL** [github/vscode-codeql#925]
**Is your feature request related to a problem? Please describe.**
I sometime runs queries in the VS Code extension that are not alerts (`@kind problem`), but want to export them to CSV for further processing, but currently the `View Results (CSV)` (right click menu) does not work for those.

**Describe the solution you'd like**
To be able to view results for any query run as CSV

**Describe alternatives you've considered**
\-

**Additional context**
I'm not sure how this will handle when multiple query predicates are in scope :shrug: I guess the extension could ask which one of them you wanted to export, but if there's an easy solution (that you can think of) to get _all of them_ I guess that would be even better.

**Comment by smowton** [comment]
> I'm not sure how this will handle when multiple query predicates are in scope 
Perhaps this isn't a right-click from the query history but rather a button in the CodeQL Query Results pane?

**Comment by aeisenberg** [comment]
Is this just about viewing a cab file? Would a separate csv viewer extension be sufficient? Like this one: https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer

**Comment by adityasharad** [comment]
Thanks! I believe we already have this tracked in https://github.com/github/vscode-codeql/issues/832, though this is a good reminder to work on it.
